### ISSUE TITLE
import akshare as ak     stock_zh_index_daily_df = ak.stock_zh_index_daily(symbol="sz399552")   print(stock_zh_index_daily_df) 运行报错

### ISSUE THREAD

**Issue by Phoenix-GR** [akfamily/akshare#2124]
File "D:\Python\lib\site-packages\akshare\__init__.py", line 2037, in <module>
    from akshare.stock_feature.stock_ttm_lyr import stock_a_ttm_lyr
  File "D:\Python\lib\site-packages\akshare\stock_feature\stock_ttm_lyr.py", line 317, in <module>
    js_functions = py_mini_racer.MiniRacer()
  File "D:\Python\lib\site-packages\py_mini_racer\py_mini_racer.py", line 168, in __init__
    self.ext = _fetch_ext_handle()
File "D:\Python\lib\site-packages\py_mini_racer\py_mini_racer.py", line 123, in _fetch_ext_handle
    raise RuntimeError("Native library not available at {}".format(EXTENSION_PATH))
RuntimeError: Native library not available at D:\Python\lib\site-packages\py_mini_racer\mini_racer.dll
Exception ignored in: <function MiniRacer.__del__ at 0x0E7F8778>
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\py_mini_racer\py_mini_racer.py", line 259, in __del__
    self.ext.mr_free_context(self.ctx)
AttributeError: 'MiniRacer' object has no attribute 'ext'

**Comment by jindaxiang** [comment]
> File "D:\Python\lib\site-packages\akshare__init__.py", line 2037, in from akshare.stock_feature.stock_ttm_lyr import stock_a_ttm_lyr File "D:\Python\lib\site-packages\akshare\stock_feature\stock_ttm_lyr.py", line 317, in js_functions = py_mini_racer.MiniRacer() File "D:\Python\lib\site-packages\py_mini_racer\py_mini_racer.py", line 168, in **init** self.ext = _fetch_ext_handle() File "D:\Python\lib\site-packages\py_mini_racer\py_mini_racer.py", line 123, in _fetch_ext_handle raise RuntimeError("Native library not available at {}".format(EXTENSION_PATH)) RuntimeError: Native library not available at D:\Python\lib\site-packages\py_mini_racer\mini_racer.dll Exception ignored in: <function MiniRacer.**del** at 0x0E7F8778> Traceback (most recent call last): File "D:\Python\lib\site-packages\py_mini_racer\py_mini_racer.py", line 259, in **del** self.ext.mr_free_context(self.ctx) AttributeError: 'MiniRacer' object has no attribute 'ext'

该接口可以正常获取数据

**Comment by Phoenix-GR** [comment]
我尝试查询股票，基金，期货等等API，都是报这个错误，重新安装pip install -U akshare或单独pip install -U py_mini_racer 也没解决
我的akshare版本为1.3.68，y_mini_racer版本为0.6.0，akTool 版本为0.0.36


报错内容中的RuntimeError: Native library not available at D:\Python\lib\site-packages\py_mini_racer\mini_racer.dll 文件我没有找到，不知道是不是这个原因。。。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Albert ***@***.***&gt;; 
发送时间: 2022年1月22日(星期六) 下午4:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [akfamily/akshare] import akshare as ak     stock_zh_index_daily_df = ak.stock_zh_index_daily(symbol=&quot;sz399552&quot;)   print(stock_zh_index_daily_df) 运行报错 (Issue #2124)





  
File "D:\Python\lib\site-packages\akshare__init__.py", line 2037, in from akshare.stock_feature.stock_ttm_lyr import stock_a_ttm_lyr File "D:\Python\lib\site-packages\akshare\stock_feature\stock_ttm_lyr.py", line 317, in js_functions = py_mini_racer.MiniRacer() File "D:\Python\lib\site-packages\py_mini_racer\py_mini_racer.py", line 168, in init self.ext = _fetch_ext_handle() File "D:\Python\lib\site-packages\py_mini_racer\py_mini_racer.py", line 123, in _fetch_ext_handle raise RuntimeError("Native library not available at {}".format(EXTENSION_PATH)) RuntimeError: Native library not available at D:\Python\lib\site-packages\py_mini_racer\mini_racer.dll Exception ignored in: <function MiniRacer.del at 0x0E7F8778&gt; Traceback (most recent call last): File "D:\Python\lib\site-packages\py_mini_racer\py_mini_racer.py", line 259, in del self.ext.mr_free_context(self.ctx) AttributeError: 'MiniRacer' object has no attribute 'ext'
  
该接口可以正常获取数据
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Phoenix-GR** [comment]
再有就是我的python版本为3.8&nbsp; 32位
在pypi 官网没有找到py_mini_racer0.6.0的32位版本，只有源码，但我不知道如何将源码打包成我想要的python3.8 的win32位whl文件




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Albert ***@***.***&gt;; 
发送时间: 2022年1月22日(星期六) 下午4:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [akfamily/akshare] import akshare as ak     stock_zh_index_daily_df = ak.stock_zh_index_daily(symbol=&quot;sz399552&quot;)   print(stock_zh_index_daily_df) 运行报错 (Issue #2124)





  
File "D:\Python\lib\site-packages\akshare__init__.py", line 2037, in from akshare.stock_feature.stock_ttm_lyr import stock_a_ttm_lyr File "D:\Python\lib\site-packages\akshare\stock_feature\stock_ttm_lyr.py", line 317, in js_functions = py_mini_racer.MiniRacer() File "D:\Python\lib\site-packages\py_mini_racer\py_mini_racer.py", line 168, in init self.ext = _fetch_ext_handle() File "D:\Python\lib\site-packages\py_mini_racer\py_mini_racer.py", line 123, in _fetch_ext_handle raise RuntimeError("Native library not available at {}".format(EXTENSION_PATH)) RuntimeError: Native library not available at D:\Python\lib\site-packages\py_mini_racer\mini_racer.dll Exception ignored in: <function MiniRacer.del at 0x0E7F8778&gt; Traceback (most recent call last): File "D:\Python\lib\site-packages\py_mini_racer\py_mini_racer.py", line 259, in del self.ext.mr_free_context(self.ctx) AttributeError: 'MiniRacer' object has no attribute 'ext'
  
该接口可以正常获取数据
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jindaxiang** [comment]
> 再有就是我的python版本为3.8&nbsp; 32位 在pypi 官网没有找到py_mini_racer0.6.0的32位版本，只有源码，但我不知道如何将源码打包成我想要的python3.8 的win32位whl文件
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Albert ***@***.***&gt;; 发送时间: 2022年1月22日(星期六) 下午4:31 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [akfamily/akshare] import akshare as ak stock_zh_index_daily_df = ak.stock_zh_index_daily(symbol=&quot;sz399552&quot;) print(stock_zh_index_daily_df) 运行报错 (Issue #2124) File "D:\Python\lib\site-packages\akshare__init__.py", line 2037, in from akshare.stock_feature.stock_ttm_lyr import stock_a_ttm_lyr File "D:\Python\lib\site-packages\akshare\stock_feature\stock_ttm_lyr.py", line 317, in js_functions = py_mini_racer.MiniRacer() File "D:\Python\lib\site-packages\py_mini_racer\py_mini_racer.py", line 168, in init self.ext = _fetch_ext_handle() File "D:\Python\lib\site-packages\py_mini_racer\py_mini_racer.py", line 123, in _fetch_ext_handle raise RuntimeError("Native library not available at {}".format(EXTENSION_PATH)) RuntimeError: Native library not available at D:\Python\lib\site-packages\py_mini_racer\mini_racer.dll Exception ignored in: <function MiniRacer.del at 0x0E7F8778&gt; Traceback (most recent call last): File "D:\Python\lib\site-packages\py_mini_racer\py_mini_racer.py", line 259, in del self.ext.mr_free_context(self.ctx) AttributeError: 'MiniRacer' object has no attribute 'ext' 该接口可以正常获取数据 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

必须是 64 位操作系统及Python
