### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by onlookor** [akfamily/akshare#2140]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本    macOS 10.15.7
2. Python 版本     3.9
3. AKShare 版本   1.3.72
4. 接口的名称和代码
>>> df=ak.stock_info_sh_delist(indicator='暂停上市公司')
5. 接口报错的截图或代码
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/akshare/stock/stock_info.py", line 306, in stock_i
nfo_sh_delist
    temp_df.columns = [
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 5491, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 70, in pandas._libs.properties.AxisProperty.__set__
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 763, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 216, in s
et_axis
    self._validate_set_axis(axis, new_labels)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/internals/base.py", line 57, in _valid
ate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本    macOS 10.15.7
> 2. Python 版本     3.9
> 3. AKShare 版本   1.3.72
> 4. 接口的名称和代码
> 
> > > > df=ak.stock_info_sh_delist(indicator='暂停上市公司')
> 
> 5. 接口报错的截图或代码
>    Traceback (most recent call last):
>    File "", line 1, in 
>    File "/usr/local/lib/python3.9/site-packages/akshare/stock/stock_info.py", line 306, in stock_i
>    nfo_sh_delist
>    temp_df.columns = [
>    File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 5491, in **setattr**
>    return object.**setattr**(self, name, value)
>    File "pandas/_libs/properties.pyx", line 70, in pandas._libs.properties.AxisProperty.**set**
>    File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 763, in _set_axis
>    self._mgr.set_axis(axis, labels)
>    File "/usr/local/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 216, in s
>    et_axis
>    self._validate_set_axis(axis, new_labels)
>    File "/usr/local/lib/python3.9/site-packages/pandas/core/internals/base.py", line 57, in _valid
>    ate_set_axis
>    raise ValueError(
>    ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
> 6. 期望获得的正确结果

感谢反馈问题，已修复，升级到 AKShare 1.3.73 版本使用
