### ISSUE TITLE
AKShare 接口问题报告 stock_em_gpzy_profile_df

### ISSUE THREAD

**Issue by zc1028** [akfamily/akshare#2302]
Traceback (most recent call last):
  File "d:\code\mysite1\jqdatapy\AKShare\akshare_test.py", line 43, in <module>
    stock_em_gpzy_profile_df = ak.stock_em_gpzy_profile()
  File "C:\Python39\lib\site-packages\akshare\stock_feature\stock_em_gpzy.py", line 43, in stock_em_gpzy_profile
    data_json = demjson.decode(data_text[data_text.find("={") + 1 :])
  File "C:\Python39\lib\site-packages\akshare\utils\demjson.py", line 5740, in decode
    result = j.decode(txt,
  File "C:\Python39\lib\site-packages\akshare\utils\demjson.py", line 4957, in decode
    raise errors[0]
akshare.utils.demjson.JSONDecodeError: Can not decode value starting with character '<'

**Comment by jindaxiang** [comment]
> Traceback (most recent call last): File "d:\code\mysite1\jqdatapy\AKShare\akshare_test.py", line 43, in stock_em_gpzy_profile_df = ak.stock_em_gpzy_profile() File "C:\Python39\lib\site-packages\akshare\stock_feature\stock_em_gpzy.py", line 43, in stock_em_gpzy_profile data_json = demjson.decode(data_text[data_text.find("={") + 1 :]) File "C:\Python39\lib\site-packages\akshare\utils\demjson.py", line 5740, in decode result = j.decode(txt, File "C:\Python39\lib\site-packages\akshare\utils\demjson.py", line 4957, in decode raise errors[0] akshare.utils.demjson.JSONDecodeError: Can not decode value starting with character '<'

感谢反馈问题，已修复该问题，请升级到 AKShare 1.4.66 使用，并参考相关文档，已经修改相关字段
