### ISSUE TITLE
债券的数据处理报错

### ISSUE THREAD

**Issue by kunagisa9** [akfamily/akshare#2360]
接口为ak.bond_spot_deal()

报错代码：
Traceback (most recent call last):
  File "pandas\_libs\lib.pyx", line 2062, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "---"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/download/stock/akshare_bond.py", line 6, in <module>
    bond_spot_deal_df = ak.bond_spot_deal()
  File "D:\anaconda\lib\site-packages\akshare\bond\china_bond.py", line 124, in bond_spot_deal
    temp_df['交易量'] = pd.to_numeric(temp_df['交易量'])
  File "D:\anaconda\lib\site-packages\pandas\core\tools\numeric.py", line 154, in to_numeric
    values = lib.maybe_convert_numeric(
  File "pandas\_libs\lib.pyx", line 2099, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "---" at position 0

我看了一下是因为获取到的债券成交量量数据写的是‘---’而不是0导致的报错

**Comment by jindaxiang** [comment]
> bond_spot_deal

感谢反馈问题，已修复该问题，请升级到 AKShare 1.4.97 版本使用
