### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by ovixiao** [akfamily/akshare#2383]
已解决！
需要把`libmini_racer.dylib`文件拷贝到对应位置，文档需要调整

--------------------

**描述遇到的问题**
1. 操作系统版本 m1 monterey 12.2.1
2. Python 版本: 3.8.9
3. AKShare 版本: 1.5.8
4. 接口的名称和代码
```
import akshare as ak

futures_pig_info_df = ak.futures_pig_info(symbol="猪肉批发价")
print(futures_pig_info_df)
```
已经按照文档描述的，下载了`libmini_racer.dylib`文件在本地
5. 接口报错的截图或代码
```
Traceback (most recent call last):
  File "/Users/xiaorixin/projects/pork/pork_ak.py", line 2, in <module>
    import akshare as ak
  File "/Users/xiaorixin/projects/pork/venv/lib/python3.8/site-packages/akshare/__init__.py", line 2270, in <module>
    from akshare.stock_feature.stock_ttm_lyr import stock_a_ttm_lyr
  File "/Users/xiaorixin/projects/pork/venv/lib/python3.8/site-packages/akshare/stock_feature/stock_ttm_lyr.py", line 317, in <module>
    js_functions = py_mini_racer.MiniRacer()
  File "/Users/xiaorixin/projects/pork/venv/lib/python3.8/site-packages/py_mini_racer/py_mini_racer.py", line 178, in __init__
    self.__class__.ext = _build_ext_handle()
  File "/Users/xiaorixin/projects/pork/venv/lib/python3.8/site-packages/py_mini_racer/py_mini_racer.py", line 125, in _build_ext_handle
    raise RuntimeError("Native library not available at {}".format(EXTENSION_PATH))
RuntimeError: Native library not available at /Users/xiaorixin/projects/pork/venv/lib/python3.8/site-packages/py_mini_racer/libmini_racer.dylib
Exception ignored in: <function MiniRacer.__del__ at 0x12bbcb5e0>
Traceback (most recent call last):
  File "/Users/xiaorixin/projects/pork/venv/lib/python3.8/site-packages/py_mini_racer/py_mini_racer.py", line 315, in __del__
    self.ext.mr_free_context(getattr(self, "ctx", None))
AttributeError: 'NoneType' object has no attribute 'mr_free_context'
```
7. 期望获得的正确结果
希望能跑通

**Comment by jindaxiang** [comment]
> 

一般放在桌面就可以了

**Comment by greysun** [comment]
> libmini_racer
请问，哪里可以下载libmini_racer.dylib文件，imac版本的与mac book版本应该不同

**Comment by zhujiayi** [comment]
libmini_racer.dylib,麻烦您把这个文件分享一下，原来那个issue文件链接被删除了，多谢
