### ISSUE TITLE
bond_cov_jsl接口无效

### ISSUE THREAD

**Issue by smartgang** [akfamily/akshare#2394]
**描述遇到的问题**
1. 操作系统版本:windows
2. Python 版本:3.7
3. AKShare 版本:最新
4. 接口的名称和代码:bond_cov_jsl
5. 接口报错的截图或代码
Traceback (most recent call last):
  File "C:/Users/smart/PycharmProjects/Timer_Task/web_convertible_data_collect.py", line 31, in <module>
    bond_cov_jsl()
  File "C:/Users/smart/PycharmProjects/Timer_Task/web_convertible_data_collect.py", line 19, in bond_cov_jsl
    bond_convert_jsl_df = ak.bond_cov_jsl(cookie="")
  File "C:\vnstudio\lib\site-packages\akshare\bond\bond_convert.py", line 67, in bond_cov_jsl
    data_json = r.json()
  File "C:\vnstudio\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\vnstudio\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "C:\vnstudio\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\vnstudio\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

更新了多次cookie都报这个错，不填cookie也报这个错，正常来讲如果不填cookie是可以取到前30条信息的，说明不是cookie的问题。

**Comment by jindaxiang** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本:windows
> 2. Python 版本:3.7
> 3. AKShare 版本:最新
> 4. 接口的名称和代码:bond_cov_jsl
> 5. 接口报错的截图或代码
>    Traceback (most recent call last):
>    File "C:/Users/smart/PycharmProjects/Timer_Task/web_convertible_data_collect.py", line 31, in 
>    bond_cov_jsl()
>    File "C:/Users/smart/PycharmProjects/Timer_Task/web_convertible_data_collect.py", line 19, in bond_cov_jsl
>    bond_convert_jsl_df = ak.bond_cov_jsl(cookie="")
>    File "C:\vnstudio\lib\site-packages\akshare\bond\bond_convert.py", line 67, in bond_cov_jsl
>    data_json = r.json()
>    File "C:\vnstudio\lib\site-packages\requests\models.py", line 898, in json
>    return complexjson.loads(self.text, **kwargs)
>    File "C:\vnstudio\lib\site-packages\simplejson__init__.py", line 525, in loads
>    return _default_decoder.decode(s)
>    File "C:\vnstudio\lib\site-packages\simplejson\decoder.py", line 370, in decode
>    obj, end = self.raw_decode(s)
>    File "C:\vnstudio\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
>    return self.scan_once(s, idx=_w(s, idx).end())
>    simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> 更新了多次cookie都报这个错，不填cookie也报这个错，正常来讲如果不填cookie是可以取到前30条信息的，说明不是cookie的问题。

感谢反馈问题，已修复该问题；升级到 AKShare 1.5.15 版本使用
