### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by CarminCol** [akfamily/akshare#2518]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本

> Windows 10专业版 21H2
2. Python 版本

> Python 3.8.12
3. AKShare 版本

> 1.5.74
4. 接口的名称和代码

> stock_info_sh_name_code_df = ak.stock_info_sh_name_code(indicator="主板A股")
5. 接口报错的截图或代码

> Traceback (most recent call last):
  File "d:\Code\data_download\test.py", line 3, in <module>
    stock_info_sh_name_code_df = ak.stock_info_sh_name_code(indicator="主板A股")
  File "C:\Users\CarminCol\anaconda3\lib\site-packages\akshare\stock\stock_info.py", line 145, in stock_info_sh_name_code
    json_data = json.loads(text_data[text_data.find("{") : -1])
  File "C:\Users\CarminCol\anaconda3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\CarminCol\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\CarminCol\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> stock_info_sh_name_code

![image](https://user-images.githubusercontent.com/18234520/168419336-f1f1986b-a212-4466-a637-d505996b3b14.png)
可以正常运行
