### ISSUE TITLE
futures_zh_spot 接口问题报告

### ISSUE THREAD

**Issue by vvutao** [akfamily/akshare#2591]
1. Windows 10
2. Python 3.8
3. AKShare 1.6.6

4. 出错接口futures_zh_spot 
        futures_zh_spot_df = ak.futures_zh_spot(symbol='V2209', market="CF", adjust='0')

5. 接口报错的截图或代码
Error
Traceback (most recent call last):
  File "C:\Users\walter\anaconda3\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "C:\Users\walter\anaconda3\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "C:\Users\walter\anaconda3\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "C:\aaasrc\cbt\test_vendor.py", line 55, in test_ak_futures_zh_spot
    futures_zh_spot_df = ak.futures_zh_spot(symbol='V2209', market="CF", adjust='0')
  File "C:\Users\walter\anaconda3\lib\site-packages\akshare\futures\futures_zh_sina.py", line 289, in futures_zh_spot
    data_df.columns = [
  File "C:\Users\walter\anaconda3\lib\site-packages\pandas\core\generic.py", line 5478, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Users\walter\anaconda3\lib\site-packages\pandas\core\generic.py", line 670, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "C:\Users\walter\anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 220, in set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 44 elements, new values have 28 elements

6. 希望该接口运行正常，谢谢。

**Comment by jindaxiang** [comment]
> 1. Windows 10
> 2. Python 3.8
> 3. AKShare 1.6.6
> 4. 出错接口futures_zh_spot
>    futures_zh_spot_df = ak.futures_zh_spot(symbol='V2209', market="CF", adjust='0')
> 5. 接口报错的截图或代码
>    Error
>    Traceback (most recent call last):
>    File "C:\Users\walter\anaconda3\lib\unittest\case.py", line 60, in testPartExecutor
>    yield
>    File "C:\Users\walter\anaconda3\lib\unittest\case.py", line 676, in run
>    self._callTestMethod(testMethod)
>    File "C:\Users\walter\anaconda3\lib\unittest\case.py", line 633, in _callTestMethod
>    method()
>    File "C:\aaasrc\cbt\test_vendor.py", line 55, in test_ak_futures_zh_spot
>    futures_zh_spot_df = ak.futures_zh_spot(symbol='V2209', market="CF", adjust='0')
>    File "C:\Users\walter\anaconda3\lib\site-packages\akshare\futures\futures_zh_sina.py", line 289, in futures_zh_spot
>    data_df.columns = [
>    File "C:\Users\walter\anaconda3\lib\site-packages\pandas\core\generic.py", line 5478, in **setattr**
>    return object.**setattr**(self, name, value)
>    File "pandas_libs\properties.pyx", line 66, in pandas._libs.properties.AxisProperty.**set**
>    File "C:\Users\walter\anaconda3\lib\site-packages\pandas\core\generic.py", line 670, in _set_axis
>    self._mgr.set_axis(axis, labels)
>    File "C:\Users\walter\anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 220, in set_axis
>    raise ValueError(
>    ValueError: Length mismatch: Expected axis has 44 elements, new values have 28 elements
> 6. 希望该接口运行正常，谢谢。

感谢反馈问题，已修复该问题，升级到 AKShare 1.6.8 版本使用
