### ISSUE TITLE
AKShare 接口问题报告-investing网站的全球指数好像不能用了

### ISSUE THREAD

**Issue by xupeixiang** [akfamily/akshare#2600]
接口示例：
`ak.index_investing_global(country="中国", index_name="富时中国A50指数", period="每日", start_date="20000101", end_date="20210909")`

Traceback (most recent call last):
  File "C:\Users\Peixi\Desktop\Codes\update.py", line 389, in <module>
    print(ak.index_investing_global(country="中国", index_name="富时中国A50指数", period="每日", start_date="20000101", end_date="20210909"))
  File "C:\anaconda3\lib\site-packages\akshare\index\index_investing.py", line 139, in index_investing_global
    name_code_dict = index_investing_global_country_name_url(country)
  File "C:\anaconda3\lib\site-packages\akshare\index\index_investing.py", line 80, in index_investing_global_country_name_url
    name_url_dict = _get_global_country_name_url()
  File "C:\anaconda3\lib\site-packages\akshare\index\index_investing.py", line 60, in _get_global_country_name_url
    name_url_option_list = soup.find("select", attrs={"name": "country"}).find_all(
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by jindaxiang** [comment]
> index_investing_global



> 富时中国A50指数

接口可以正常使用，请按文档说明操作
