### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Easyzhan** [akfamily/akshare#2645]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本  macos nonterey
2. Python 版本  3.8
3. AKShare 版本 最新版
4. 接口的名称和代码

stock_changes_rock_df = ak.stock_changes_em(symbol="火箭发射")
print(stock_changes_rock_df)

6.  接口报错的截图或代码
7. 期望获得的正确结果

Traceback (most recent call last):
  File "/Users/natsu/Music/stockfucker/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/natsu/Music/stockfucker/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/natsu/Music/stockfucker/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natsu/Music/stockfucker/venv/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/natsu/Music/stockfucker/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/natsu/Music/stockfucker/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=7890): Max retries exceeded with url: http://push2ex.eastmoney.com/getTopicZTPool?ut=7eea3edcaed734bea9cbfc24409ed989&dpt=wz.ztzt&Pageindex=0&pagesize=10000&sort=fbt%3Aasc&date=20220620&_=1621590489736 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natsu/Music/stockfucker/stock/ak1000/AKBang.py", line 14, in <module>
    stock_zt_pool_em_df = ak.stock_zt_pool_em(date=date)
  File "/Users/natsu/Music/stockfucker/venv/lib/python3.8/site-packages/akshare/stock_feature/stock_ztb_em.py", line 38, in stock_zt_pool_em
    r = requests.get(url, params=params)
  File "/Users/natsu/Music/stockfucker/venv/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/natsu/Music/stockfucker/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/natsu/Music/stockfucker/venv/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/natsu/Music/stockfucker/venv/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/natsu/Music/stockfucker/venv/lib/python3.8/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=7890): Max retries exceeded with url: http://push2ex.eastmoney.com/getTopicZTPool?ut=7eea3edcaed734bea9cbfc24409ed989&dpt=wz.ztzt&Pageindex=0&pagesize=10000&sort=fbt%3Aasc&date=20220620&_=1621590489736 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

**Comment by jindaxiang** [comment]
> stock_changes_em

接口测试正常，建议检查本地环境配置

**Comment by Easyzhan** [comment]
是不是Python版本需要更新，现在是3.8
