### ISSUE TITLE
郑商所-日交易数据接口报错

### ISSUE THREAD

**Issue by Kinghts** [akfamily/akshare#2663]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
`win10`
2. Python 版本
`3.9.7`
3. AKShare 版本
`1.6.31`
4. 接口的名称和代码
`ak.get_futures_daily("20100824", "20100824", market="CZCE")`
5. 接口报错的截图或代码
HTTP 412错误，但是浏览器访问是有数据的；
测试发现20100824及之前的日期是这种报错。
详细：
`Traceback (most recent call last):
  File "D:\test\test.py", line 3, in <module>
    df = ak.get_futures_daily("20100106", "20100106", market="CZCE")
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\akshare\futures\futures_daily_bar.py", line 553, in get_futures_daily
    df = f(date=str(start_date).replace("-", ""))
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\akshare\futures\futures_daily_bar.py", line 272, in get_czce_daily
    df = pd.read_html(url)[1].dropna(how="any")
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper       
    return func(*args, **kwargs)
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\html.py", line 1098, in read_html
    return _parse(
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\html.py", line 906, in _parse
    tables = p.parse_tables()
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\html.py", line 222, in parse_tables
    tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\html.py", line 745, in _build_doc
    raise e
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\html.py", line 726, in _build_doc
    with urlopen(self.io) as f:
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\common.py", line 212, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 412: Precondition Failed`
6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    `win10`
> 2. Python 版本
>    `3.9.7`
> 3. AKShare 版本
>    `1.6.31`
> 4. 接口的名称和代码
>    `ak.get_futures_daily("20100824", "20100824", market="CZCE")`
> 5. 接口报错的截图或代码
>    HTTP 412错误，但是浏览器访问是有数据的；
>    测试发现20100824及之前的日期是这种报错。
>    详细：
>    `Traceback (most recent call last):   File "D:\test\test.py", line 3, in <module> df = ak.get_futures_daily("20100106", "20100106", market="CZCE")   File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\akshare\futures\futures_daily_bar.py", line 553, in get_futures_daily df = f(date=str(start_date).replace("-", ""))   File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\akshare\futures\futures_daily_bar.py", line 272, in get_czce_daily df = pd.read_html(url)[1].dropna(how="any")   File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper        return func(*args, **kwargs)   File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\html.py", line 1098, in read_html return _parse(   File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\html.py", line 906, in _parse tables = p.parse_tables()   File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\html.py", line 222, in parse_tables tables = self._parse_tables(self._build_doc(), self.match, self.attrs)   File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\html.py", line 745, in _build_doc raise e   File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\html.py", line 726, in _build_doc with urlopen(self.io) as f:   File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\common.py", line 212, in urlopen return urllib.request.urlopen(*args, **kwargs)   File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen return opener.open(url, data, timeout)   File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open response = meth(req, response)   File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response response = self.parent.error(   File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error return self._call_chain(*args)   File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain result = func(*args)   File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 412: Precondition Failed`
> 6. 期望获得的正确结果

感谢反馈问题，已修复该问题，升级到 AKShare 1.6.32 版本使用
