### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by zwj-lambda** [akfamily/akshare#2734]
1. 操作系统版本 win10
2. Python 版本 Python 3.8.3
3. AKShare 版本 1.6.53 
4. Pandas 版本 1.4.2
5. 接口的名称和代码 
ak.get_futures_daily('20220713', '20220714', 'DCE')
6. 接口报错的截图或代码
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-2a88069925cf>", line 1, in <module>
    repr(ak.get_futures_daily(self._beg, self._end, market=self._ex))
  File "C:\Users\zwj\AppData\Roaming\Python\Python38\site-packages\akshare\futures\futures_daily_bar.py", line 657, in get_futures_daily
    df = f(date=str(start_date).replace("-", ""))
  File "C:\Users\zwj\AppData\Roaming\Python\Python38\site-packages\akshare\futures\futures_daily_bar.py", line 552, in get_dce_daily
    data_df = pd.read_excel(BytesIO(r.content))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\excel\_base.py", line 457, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\excel\_base.py", line 1380, in __init__
    raise ValueError(
ValueError: Excel file format cannot be determined, you must specify an engine manually.

**Comment by jindaxiang** [comment]
> 1. 操作系统版本 win10
> 2. Python 版本 Python 3.8.3
> 3. AKShare 版本 1.6.53
> 4. Pandas 版本 1.4.2
> 5. 接口的名称和代码
>    ak.get_futures_daily('20220713', '20220714', 'DCE')
> 6. 接口报错的截图或代码
>    Traceback (most recent call last):
>    File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
>    exec(code_obj, self.user_global_ns, self.user_ns)
>    File "", line 1, in 
>    repr(ak.get_futures_daily(self._beg, self._end, market=self._ex))
>    File "C:\Users\zwj\AppData\Roaming\Python\Python38\site-packages\akshare\futures\futures_daily_bar.py", line 657, in get_futures_daily
>    df = f(date=str(start_date).replace("-", ""))
>    File "C:\Users\zwj\AppData\Roaming\Python\Python38\site-packages\akshare\futures\futures_daily_bar.py", line 552, in get_dce_daily
>    data_df = pd.read_excel(BytesIO(r.content))
>    File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\util_decorators.py", line 311, in wrapper
>    return func(*args, **kwargs)
>    File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\excel_base.py", line 457, in read_excel
>    io = ExcelFile(io, storage_options=storage_options, engine=engine)
>    File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\excel_base.py", line 1380, in **init**
>    raise ValueError(
>    ValueError: Excel file format cannot be determined, you must specify an engine manually.

大商所的所有接口由于大商所增加了加密方式，暂时无法使用
