### ISSUE TITLE
crypto_hist接口报错

### ISSUE THREAD

**Issue by bluntos** [akfamily/akshare#2763]
Python Version: 3.8.13
akshare: 1.6.44

import akshare as ak
ak.crypto_hist('BTC')

Traceback (most recent call last):
  File "/home/lgwang/anaconda3/envs/bi/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index_class_helper.pxi", line 105, in pandas._libs.index.Int64Engine._check_type
  File "pandas/_libs/index_class_helper.pxi", line 105, in pandas._libs.index.Int64Engine._check_type
KeyError: '日期'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/lgwang/anaconda3/envs/bi/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-17a8def3c908>", line 1, in <cell line: 1>
    ak.crypto_hist('BTC')
  File "/home/lgwang/anaconda3/envs/bi/lib/python3.8/site-packages/akshare/crypto/crypto_hist_investing.py", line 182, in crypto_hist
    df_data.index = pd.to_datetime(df_data["日期"], format="%Y年%m月%d日")
  File "/home/lgwang/anaconda3/envs/bi/lib/python3.8/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/lgwang/anaconda3/envs/bi/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err

**Comment by jindaxiang** [comment]
> 

请查看接口相关文档，需要通过代理使用
