### ISSUE TITLE
py3.10.5无法使用akshare1.6.64

### ISSUE THREAD

**Issue by anliming** [akfamily/akshare#2887]
(venv) (base) apple@localhost:~/PycharmProjects/mysite$ python
Python 3.10.5 (v3.10.5:f377153967, Jun  6 2022, 12:36:10) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import akshare as ak
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/apple/PycharmProjects/p310/venv/lib/python3.10/site-packages/akshare/__init__.py", line 2798, in <module>
    from akshare.index.index_kq_fz import index_kq_fz
  File "/Users/apple/PycharmProjects/p310/venv/lib/python3.10/site-packages/akshare/index/index_kq_fz.py", line 11, in <module>
    from akshare.utils.ak_session import session
  File "/Users/apple/PycharmProjects/p310/venv/lib/python3.10/site-packages/akshare/utils/ak_session.py", line 8, in <module>
    from requests_cache import CachedSession
  File "/Users/apple/PycharmProjects/p310/venv/lib/python3.10/site-packages/requests_cache/__init__.py", line 7, in <module>
    from .backends import *
  File "/Users/apple/PycharmProjects/p310/venv/lib/python3.10/site-packages/requests_cache/backends/__init__.py", line 7, in <module>
    from .base import BaseCache, BaseStorage, DictStorage
  File "/Users/apple/PycharmProjects/p310/venv/lib/python3.10/site-packages/requests_cache/backends/base.py", line 18, in <module>
    from ..serializers import init_serializer
  File "/Users/apple/PycharmProjects/p310/venv/lib/python3.10/site-packages/requests_cache/serializers/__init__.py", line 4, in <module>
    from .cattrs import CattrStage
  File "/Users/apple/PycharmProjects/p310/venv/lib/python3.10/site-packages/requests_cache/serializers/cattrs.py", line 17, in <module>
    from cattr import GenConverter
ModuleNotFoundError: No module named 'cattr'

--------------------

(venv) (base) apple@localhost:~/PycharmProjects/mysite$ pip list
Package               Version
--------------------- -----------
**akshare               1.6.64**
appdirs               1.4.4
appnope               0.1.3
asgiref               3.5.2
asttokens             2.0.5
attrs                 21.4.0
backcall              0.2.0
beautifulsoup4        4.11.1
bokeh                 2.4.3
**cattrs                22.1.0**
certifi               2022.6.15

**Comment by anliming** [comment]
在py3.9.7下可以用。


akshare和cattrs的版本相同，在3.10.5下就不可以了

akshare               1.6.75
cattrs                22.1.0

不知道是不是我的环境问题。

**Comment by anliming** [comment]
问题已解决。 我用docker下载了干净的py3.10.5版本，测试ak没问题。  

重新安装了cattrs解决的。
