### ISSUE TITLE
股票回购接口报错

### ISSUE THREAD

**Issue by LI-Jialu** [akfamily/akshare#2908]
**问题描述**
使用`stock_repurchase_em()`无法获取回测数据

**复现**
代码为： ` stock_repurchase_em_df = ak.stock_repurchase_em()`
报错为： 
~~~
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\akshare\stock\stock_repurchase_em.py", line 32, in stock_repurchase_em
    total_page = data_json["result"]["pages"]
TypeError: 'NoneType' object is not subscriptable
~~~

**版本信息**
 - OS:  Win 11 
 - Browser: Chrome 
 - Version: Python 3.9.7

**Comment by LI-Jialu** [comment]
已自己解决，稍后提一个PR。

**Comment by LI-Jialu** [comment]
问题在于：东方财富网站api更改，内部数据库表单名更新。

**Comment by jindaxiang** [comment]
> 问题在于：东方财富网站api更改，内部数据库表单名更新。

已更新相关接口，升级到 AKShare 1.7.12 使用
