### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by wangfeiily** [akfamily/akshare#2916]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 Win10 64
2. Python 版本 3.9
3. AKShare 版本 1.7.13
4. 接口的名称和代码   sw_index_daily(symbol="801011", start_date="2022-08-01", end_date="2022-08-30")
5. 接口报错的截图或代码 
   raceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\workspace\Barra-master\ReturnAttribution.py", line 211, in <module>
    data = ak.sw_index_daily(symbol="801011", start_date="2022-08-01", end_date="2022-08-30")
  File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\akshare\index\index_sw.py", line 246, in sw_index_daily
    temp_df["date"] = pd.to_datetime(temp_df["date"]).dt.date
  File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\core\frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'date'

6.  期望获得的正确结果 希望获取正确的值

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 Win10 64
> 2. Python 版本 3.9
> 3. AKShare 版本 1.7.13
> 4. 接口的名称和代码   sw_index_daily(symbol="801011", start_date="2022-08-01", end_date="2022-08-30")
> 5. 接口报错的截图或代码
>    raceback (most recent call last):
>    File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
>    return self._engine.get_loc(casted_key)
>    File "pandas_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
>    File "pandas_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
>    File "pandas_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
>    File "pandas_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
>    KeyError: 'date'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "D:\workspace\Barra-master\ReturnAttribution.py", line 211, in data = ak.sw_index_daily(symbol="801011", start_date="2022-08-01", end_date="2022-08-30") File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\akshare\index\index_sw.py", line 246, in sw_index_daily temp_df["date"] = pd.to_datetime(temp_df["date"]).dt.date File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\core\frame.py", line 3505, in **getitem** indexer = self.columns.get_loc(key) File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc raise KeyError(key) from err KeyError: 'date'
> 
> 6. 期望获得的正确结果 希望获取正确的值

见文档接口说明

**Comment by solecloud** [comment]
Same question.
Really appreciate if someone could help to solve it.

**Comment by solecloud** [comment]
import akshare as ak
ak.sw_index_daily(symbol="801011", start_date="2022-08-01", end_date="2022-08-30"

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/lenovo/Documents/MATLAB/calApp/akswData/test0906.py", line 3, in <module>
    ak.sw_index_daily(symbol="801011", start_date="2022-08-01", end_date="2022-08-30")
  File "C:\ProgramData\Anaconda3\lib\site-packages\akshare\index\index_sw.py", line 246, in sw_index_daily
    temp_df["date"] = pd.to_datetime(temp_df["date"]).dt.date
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'date'

Process finished with exit code 1

**Comment by solecloud** [comment]
请问是哪里的文档接口说明解决了该问题，没看明白
