### ISSUE TITLE
The script doesn't work

### ISSUE THREAD

**Issue by solecloud** [akfamily/akshare#2933]
input:
import akshare as ak
sw_index_daily_df = ak.sw_index_daily(symbol="801011",start_date="20191201",end_date="20201207")
sw_index_daily_df.to_csv('sw_index_daily.csv', encoding='ansi')

the error info:
Traceback (most recent call last):
  File "C:\Users\lenovo\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\MATLAB\calApp\akswData\test0906.py", line 2, in <module>
    sw_index_daily_df = ak.sw_index_daily(symbol="801011",start_date="20191201",end_date="20201207")
  File "C:\Users\lenovo\anaconda3\lib\site-packages\akshare\index\index_sw.py", line 246, in sw_index_daily
    temp_df["date"] = pd.to_datetime(temp_df["date"]).dt.date
  File "C:\Users\lenovo\anaconda3\lib\site-packages\pandas\core\frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\lenovo\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'date'

Process finished with exit code 1

**Comment by jindaxiang** [comment]
> input: import akshare as ak sw_index_daily_df = ak.sw_index_daily(symbol="801011",start_date="20191201",end_date="20201207") sw_index_daily_df.to_csv('sw_index_daily.csv', encoding='ansi')
> 
> the error info: Traceback (most recent call last): File "C:\Users\lenovo\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc return self._engine.get_loc(casted_key) File "pandas_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc File "pandas_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc File "pandas_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item File "pandas_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item KeyError: 'date'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "C:\Users\lenovo\Documents\MATLAB\calApp\akswData\test0906.py", line 2, in sw_index_daily_df = ak.sw_index_daily(symbol="801011",start_date="20191201",end_date="20201207") File "C:\Users\lenovo\anaconda3\lib\site-packages\akshare\index\index_sw.py", line 246, in sw_index_daily temp_df["date"] = pd.to_datetime(temp_df["date"]).dt.date File "C:\Users\lenovo\anaconda3\lib\site-packages\pandas\core\frame.py", line 3505, in **getitem** indexer = self.columns.get_loc(key) File "C:\Users\lenovo\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc raise KeyError(key) from err KeyError: 'date'
> 
> Process finished with exit code 1

Please pay attention to interface docs
