### ISSUE TITLE
报bug：stock_zh_index_spot接口报错

### ISSUE THREAD

**Issue by jenerse** [akfamily/akshare#2948]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.local/share/virtualenvs/agu-5NQDdpah/lib/python3.8/site-packages/akshare/index/zh_stock_index_sina.py", line 69, in stock_zh_index_spot
    data_json = demjson.decode(res.text)
  File "/root/.local/share/virtualenvs/agu-5NQDdpah/lib/python3.8/site-packages/akshare/utils/demjson.py", line 5740, in decode
    result = j.decode(txt,
  File "/root/.local/share/virtualenvs/agu-5NQDdpah/lib/python3.8/site-packages/akshare/utils/demjson.py", line 4957, in decode
    raise errors[0]
akshare.utils.demjson.JSONDecodeError: Can not decode value starting with character '<'

**Comment by jindaxiang** [comment]
> Traceback (most recent call last): File "", line 1, in File "/root/.local/share/virtualenvs/agu-5NQDdpah/lib/python3.8/site-packages/akshare/index/zh_stock_index_sina.py", line 69, in stock_zh_index_spot data_json = demjson.decode(res.text) File "/root/.local/share/virtualenvs/agu-5NQDdpah/lib/python3.8/site-packages/akshare/utils/demjson.py", line 5740, in decode result = j.decode(txt, File "/root/.local/share/virtualenvs/agu-5NQDdpah/lib/python3.8/site-packages/akshare/utils/demjson.py", line 4957, in decode raise errors[0] akshare.utils.demjson.JSONDecodeError: Can not decode value starting with character '<'

新浪接口需要增加时间间隔
