### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by gangzi3** [akfamily/akshare#2953]
AKShare版本最新的, python版本3.9.5, py-mini-racer版本最新的, pandas版本最新的, 代码:
import akshare as ak
print(123)
打包成.exe后报错:
Traceback (most recent call last):
  File "test_5.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "akshare\__init__.py", line 2843, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "akshare\index\index_kq_fz.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "akshare\utils\ak_session.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests_cache\__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests_cache\backends\__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests_cache\backends\base.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests_cache\serializers\__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests_cache\serializers\preconf.py", line 122, in <module>
  File "requests_cache\serializers\pipeline.py", line 44, in __init__
  File "requests_cache\serializers\pipeline.py", line 44, in <listcomp>
AttributeError: type object 'Placeholder' has no attribute 'loads'
[20560] Failed to execute script 'test_5' due to unhandled exception!

**Comment by jindaxiang** [comment]
> AKShare版本最新的, python版本3.9.5, py-mini-racer版本最新的, pandas版本最新的, 代码: import akshare as ak print(123) 打包成.exe后报错: Traceback (most recent call last): File "test_5.py", line 1, in File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module File "akshare__init__.py", line 2843, in File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module File "akshare\index\index_kq_fz.py", line 11, in File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module File "akshare\utils\ak_session.py", line 8, in File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module File "requests_cache__init__.py", line 7, in File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module File "requests_cache\backends__init__.py", line 7, in File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module File "requests_cache\backends\base.py", line 18, in File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module File "requests_cache\serializers__init__.py", line 6, in File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module File "requests_cache\serializers\preconf.py", line 122, in File "requests_cache\serializers\pipeline.py", line 44, in **init** File "requests_cache\serializers\pipeline.py", line 44, in AttributeError: type object 'Placeholder' has no attribute 'loads' [20560] Failed to execute script 'test_5' due to unhandled exception!

不建议打包封装，建议使用 AKTools

**Comment by gangzi3** [comment]
> > AKShare最新版本, python3.9.5, py-mini-racer最新版本, pandas最新版本, 代码: import akshare as ak print(123) 打包成.exe后报错: Traceback (最近一次调用最后一次):文件“test_5.py”，第 1 行，文件“”，第 1007 行，_find_and_load 文件“”，第 986 行，_find_and_load_unlocked 文件“”，第 680 行，_load_unlocked 文件“PyInstaller\loader\pyimod03_importers.py”，行495，在 exec_module 文件中“akshare__init__.py”，第 2843 行，在文件“”中，第 1007 行，在 _find_and_load 文件中“”，第 986 行，在 _find_and_load_unlocked 文件中“”，第 680 行，在 _load_unlocked 文件中“PyInstaller\loader\pyimod03_importers.py”，第 495 行，在exec_module 文件“akshare\index\index_kq_fz.py”，第 11 行，在文件“”中，第 1007 行，在 _find_and_load 文件中“”，第 986 行，在 _find_and_load_unlocked 文件中“”，第 680 行，在 _load_unlocked 文件中“PyInstaller\loader\pyimod03_importers .py"，第 495 行，在 exec_module 文件中 "akshare\utils\ak_session.py"，第 8 行，在文件""中，第 1007 行，在 _find_and_load 文件中""，第 986 行，在_find_and_load_unlocked 文件中""，第 680 行，在_load_unlocked 文件“PyInstaller\loader\pyimod03_importers.py”，第 495 行，__在 exec_module 文件“requests_cache__init .py”中，第 7 行，在文件“”中，第 1007 行，在 _find_and_load 文件“”中，第 986 行，在_find_and_load_unlocked 文件“”，第 680 行，_load_unlocked 文件“PyInstaller\loader\pyimod03_importers.py”，第 495 行，exec_module 文件“requests_cache\backends__init__ .py”，第 7 行，文件“”，第 1007 行，_find_and_load 文件“ "，第 986 行，在 _find_and_load_unlocked 文件中 ""，第 680 行，在 _load_unlocked 文件中 "PyInstaller\loader\pyimod03_importers.py"，第 495 行，在 exec_module 文件中 "re​​quests_cache\backends\base.py"，第 18 行，在文件中 "" ，第 1007 行，在 _find_and_load 文件“”中，第 986 行，在_find_and_load_unlocked 文件中“”，第 680 行，在_load_unlocked 文件中“PyInstaller\loader\pyimod03_importers.py”，第 495 行，在 exec_module 文件中“requests_cache\serializers__init”__.py"，第 6 行，在文件 ""，第 1007 行，在 _find_and_load 文件中 ""，第 986 行，在 _find_and_load_unlocked 文件中""，第 680 行，在 _load_unlocked 文件中 "PyInstaller\loader\pyimod03_importers.py"，第 495 行，在exec_module 文件“requests_cache\serializers\preconf.py”，第 122 行，文件“requests_cache\serializers\pipeline.py”，第 44 行，**init**文件“requests_cache\serializers\pipeline.py”，第 44 行，在 AttributeError 中：类型对象“占位符”没有属性“加载”[20560] 由于未处理的异常，无法执行脚本“test_5”！
> 
> 不建议打包，建议使用 AKTools

真的没有任何办法了吗, 程序都已经写完了, 就差打包了, 如果用AKTools又得重新弄

**Comment by rovoskarl** [comment]
@gangzi3  你好打包解决了吗
