### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by renzhang** [akfamily/akshare#2975]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
Ubuntu Server v22.04.1

2. Python 版本
Python 3.10.6

3. AKShare 版本
akshare version: 1.7.30

4. 接口的名称和代码
import akshare as ak
print(f'akshare version: {ak.__version__}')

fund_portfolio_hold_em_df = ak.fund_portfolio_hold_em(symbol="000001", date="2021")
print(fund_portfolio_hold_em_df)

5. 接口报错的截图或代码
Traceback (most recent call last):
  File "/home/zhangr/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3800, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '占净值比例'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zhangr/coding/python/test_akshare.py", line 25, in <module>
    fund_portfolio_hold_em_df = ak.fund_portfolio_hold_em(symbol="000001", date="2020")
  File "/home/zhangr/.local/lib/python3.10/site-packages/akshare/fund/fund_portfolio_em.py", line 52, in fund_portfolio_hold_em
    temp_df["占净值比例"].str.split("%", expand=True).iloc[:, 0]
  File "/home/zhangr/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/zhangr/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    raise KeyError(key) from err
KeyError: '占净值比例'

6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> fund_portfolio_hold_em

该接口可以正常获取数据
