### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by ISayTT** [akfamily/akshare#2982]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本  Windows 11
2. Python 版本  3.8.5
3. AKShare 版本   最新 1.7.30
4. 接口的名称和代码            
 sw_index_daily                   申万一级、二级历史行情
 sw_index_daily_indicator   申万一级、二级历史行情指标
5. 接口报错的截图或代码

**代码/Code:**
df1 = ak.sw_index_daily(symbol = "801010", start_date= "20220101", end_date="20220927")
df2 = ak.sw_index_daily(symbol = "801010", start_date= "20220101", end_date="20220927",data_type="Week")

**报错信息：KeyError: 'date'**
具体信息：
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\申万\venv\lib\site-packages\pandas\core\indexes\base.py", line 3800, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'date'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "D:\python3.8.5\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "E:\PyCharm 2020.3.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "E:\PyCharm 2020.3.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Lenovo/Desktop/申万/Main.py", line 6, in <module>
    df = ak.sw_index_daily(symbol = "801010", start_date= "20220101", end_date="20220927")
  File "C:\Users\Lenovo\Desktop\申万\venv\lib\site-packages\akshare\index\index_sw.py", line 246, in sw_index_daily
    temp_df["date"] = pd.to_datetime(temp_df["date"]).dt.date
  File "C:\Users\Lenovo\Desktop\申万\venv\lib\site-packages\pandas\core\frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\Lenovo\Desktop\申万\venv\lib\site-packages\pandas\core\indexes\base.py", line 3802, in get_loc
    raise KeyError(key) from err
KeyError: 'date'

6.期望获得的正确结果
解决报错

**Comment by jindaxiang** [comment]
> sw_index_daily

建议先看下接口文档，该接口暂时不能获取数据

**Comment by ISayTT** [comment]
好的，谢谢大佬！
