### ISSUE TITLE
stock_a_all_pb  can't work

### ISSUE THREAD

**Issue by shij10** [akfamily/akshare#3013]
https://github.com/akfamily/akshare/blob/21e5fcd74259f9061a4cb9043c23b6ffeaf697e2/akshare/stock_feature/stock_all_pb.py#L339

the 'marketId' column doesn't exist in df
 

```
>>> stock_a_all_pb_df = ak.stock_a_all_pb()
Traceback (most recent call last):
  File "C:\Users\shij10\Miniconda3\envs\tsquant\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'marketId'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\shij10\Miniconda3\envs\tsquant\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\shij10\Miniconda3\envs\tsquant\lib\site-packages\akshare\stock_feature\stock_all_pb.py", line 339, in stock_a_all_pb
    del temp_df['marketId']
  File "C:\Users\shij10\Miniconda3\envs\tsquant\lib\site-packages\pandas\core\generic.py", line 3963, in __delitem__
    loc = self.axes[-1].get_loc(key)
  File "C:\Users\shij10\Miniconda3\envs\tsquant\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
```

**Comment by jindaxiang** [comment]
> https://github.com/akfamily/akshare/blob/21e5fcd74259f9061a4cb9043c23b6ffeaf697e2/akshare/stock_feature/stock_all_pb.py#L339
> 
> the 'marketId' column doesn't exist in df
> 
> ```
> >>> stock_a_all_pb_df = ak.stock_a_all_pb()
> Traceback (most recent call last):
>   File "C:\Users\shij10\Miniconda3\envs\tsquant\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
>     return self._engine.get_loc(casted_key)
>   File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'marketId'
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
>   File "C:\Users\shij10\Miniconda3\envs\tsquant\lib\code.py", line 90, in runcode
>     exec(code, self.locals)
>   File "<input>", line 1, in <module>
>   File "C:\Users\shij10\Miniconda3\envs\tsquant\lib\site-packages\akshare\stock_feature\stock_all_pb.py", line 339, in stock_a_all_pb
>     del temp_df['marketId']
>   File "C:\Users\shij10\Miniconda3\envs\tsquant\lib\site-packages\pandas\core\generic.py", line 3963, in __delitem__
>     loc = self.axes[-1].get_loc(key)
>   File "C:\Users\shij10\Miniconda3\envs\tsquant\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
>     raise KeyError(key) from err
> ```

感谢反馈问题；已修复该问题，升级到 AKShare 1.7.43 版本使用
