### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by ferriswang** [akfamily/akshare#3032]
ak.stock_lhb_stock_detail_em
接口自十一假期之后，连接不上

**Comment by jindaxiang** [comment]
> ak.stock_lhb_stock_detail_em 接口自十一假期之后，连接不上

接口可以正常使用；需要通过 ak.stock_lhb_stock_detail_date_em(symbol="600077") 接口获取相应股票的有龙虎榜详情数据的日期

**Comment by ferriswang** [comment]
试了，ak. stock_lhb_stock_detail_date_em 这个接口也报同样的网络错误，除龙虎榜接口外，其他接口正常，应该是这个接口出问题了，您可以测试一下。

**Comment by jindaxiang** [comment]
> 

提供下具体报错的代码

**Comment by ferriswang** [comment]
程序代码：

**Comment by ferriswang** [comment]
程序代码：
import akshare as ak
#df = ak.stock_lhb_stock_detail_em(symbol='002901', date='20221012', flag='买入')
df = ak.stock_lhb_stock_detail_date_em(symbol="002901")
print(df)

问题描述：
一直使用stock_lhb_stock_detail_em接口。8月份之前，响应时间为秒级，自8月1号开始，单次请求响应突然很慢，10分钟左右，但能正常返回数据。10月10号开始，响应时间依然很慢，且最终报错（ak.stock_lhb_stock_detail_em与ak.stock_lhb_stock_detail_date_em方法报错内容一样），本次运行上述程序，15分钟后报错：
python3 test.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa1c4d27100>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='datacenter-web.eastmoney.com', port=443): Max retries exceeded with url: /api/data/v1/get?reportName=RPT_LHB_BOARDDATE&columns=SECURITY_CODE%2CTRADE_DATE%2CTR_DATE&filter=%28SECURITY_CODE%3D%22002901%22%29&pageNumber=1&pageSize=1000&sortTypes=-1&sortColumns=TRADE_DATE&source=WEB&client=WEB (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa1c4d27100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    df = ak.stock_lhb_stock_detail_date_em(symbol="002901")
  File "/usr/local/lib/python3.8/site-packages/akshare/stock_feature/stock_lhb_em.py", line 364, in stock_lhb_stock_detail_date_em
    r = requests.get(url, params=params)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='datacenter-web.eastmoney.com', port=443): Max retries exceeded with url: /api/data/v1/get?reportName=RPT_LHB_BOARDDATE&columns=SECURITY_CODE%2CTRADE_DATE%2CTR_DATE&filter=%28SECURITY_CODE%3D%22002901%22%29&pageNumber=1&pageSize=1000&sortTypes=-1&sortColumns=TRADE_DATE&source=WEB&client=WEB (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa1c4d27100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

**Comment by jindaxiang** [comment]
> 容一样），本次运行上述程序，15分钟

该股票数据源没有数据

**Comment by ferriswang** [comment]
https://data.eastmoney.com/stock/lhb/002901.html

**Comment by ferriswang** [comment]
我按你们文档写的目标地址，把这支代码拼进去，002901，日期20221012是有数据的呀

**Comment by ferriswang** [comment]
平时每天是先找涨停板的票，再依次调用龙虎榜数据，结果都报错，不可能全没有数据吧

**Comment by jindaxiang** [comment]
> 20221012

![image](https://user-images.githubusercontent.com/18234520/195804136-94ff10ce-f06d-4269-a742-26ca3e4a96a9.png)

**Comment by ferriswang** [comment]
1. 看结果12号不是有的吗
2. 是我的调用方式不对吗，我是这样调用的（按文档上说的）：
import akshare as ak
df = ak.stock_lhb_stock_detail_date_em(symbol="002901")

**Comment by jindaxiang** [comment]
> 1. 看结果12号不是有的吗
> 2. 是我的调用方式不对吗，我是这样调用的（按文档上说的）：
>    import akshare as ak
>    df = ak.stock_lhb_stock_detail_date_em(symbol="002901")

检查下你本地 Python 环境和安装的 AKShare 的版本

**Comment by ferriswang** [comment]
python3.8, akshare已升至最新版本，还是不行
