### ISSUE TITLE
AKShare 接口问题报告: 下载数据出错，没有数据返回

### ISSUE THREAD

**Issue by aiot-tech** [akfamily/akshare#3136]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本: ubuntu18.04
2. Python 版本: python3.9.12
3. AKShare 版本: akshare-1.7.79
4. 接口的名称和代码: ak.stock_zh_a_daily
5. 接口报错的截图或代码
```
Traceback (most recent call last):
  File "data_tool.py", line 109, in down_data
    stock_his_df = ak.stock_zh_a_daily(symbol=stock_code, start_date=start_date, end_date=cur_date,
  File "lib/python3.9/site-packages/akshare/stock/stock_zh_a_sina.py", line 19, in stock_zh_a_daily
    amount_data_json = demjson.decode(
  File "lib/python3.9/site-packages/akshare/utils/demjson.py", line 5740, in decode
    result = j.decode(txt,
  File "lib/python3.9/site-packages/akshare/utils/demjson.py", line 4957, in decode
    raise errors[0]
akshare.utils.demjson.JSONDecodeError: No value to decode
```
6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> 4\. stock_zh_a_daily

接口测试正常
