### ISSUE TITLE
大佬好,ak.stock_em_pg()东方财富配股接口报错

### ISSUE THREAD

**Issue by dalongchen** [akfamily/akshare#3203]
Traceback (most recent call last):
  File "/home/chen/Documents/my220812/stock/test.py", line 536, in <module>
    stock_em_pg()
  File "/home/chen/Documents/my220812/stock/global_variable.py", line 9, in new_func
    res = func(*arg, **kw)
  File "/home/chen/Documents/my220812/stock/test.py", line 528, in stock_em_pg
    st = ak.stock_em_pg()
  File "/home/chen/miniconda3/lib/python3.9/site-packages/akshare/stock_feature/stock_zf_pg.py", line 100, in stock_em_pg
    data_json = demjson.decode(data_text[1:-1])
  File "/home/chen/miniconda3/lib/python3.9/site-packages/akshare/utils/demjson.py", line 5740, in decode
    result = j.decode(txt,
  File "/home/chen/miniconda3/lib/python3.9/site-packages/akshare/utils/demjson.py", line 4957, in decode
    raise errors[0]
akshare.utils.demjson.JSONDecodeError: Can not decode value starting with character '!'

**Comment by jindaxiang** [comment]
> Traceback (most recent call last): File "/home/chen/Documents/my220812/stock/test.py", line 536, in stock_em_pg() File "/home/chen/Documents/my220812/stock/global_variable.py", line 9, in new_func res = func(*arg, **kw) File "/home/chen/Documents/my220812/stock/test.py", line 528, in stock_em_pg st = ak.stock_em_pg() File "/home/chen/miniconda3/lib/python3.9/site-packages/akshare/stock_feature/stock_zf_pg.py", line 100, in stock_em_pg data_json = demjson.decode(data_text[1:-1]) File "/home/chen/miniconda3/lib/python3.9/site-packages/akshare/utils/demjson.py", line 5740, in decode result = j.decode(txt, File "/home/chen/miniconda3/lib/python3.9/site-packages/akshare/utils/demjson.py", line 4957, in decode raise errors[0] akshare.utils.demjson.JSONDecodeError: Can not decode value starting with character '!'

感谢反馈问题；已修复该问题，升级到 AKShare 1.8.3 版本使用
