### ISSUE TITLE
function issue

### ISSUE THREAD

**Issue by wind4321** [akfamily/akshare#3230]
When I call functions sw_index_spot() and sw_index_second_spot(), it shows:

sw_index_spot_df = ak.sw_index_spot()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/aporchid08/lib/python3.7/site-packages/akshare/index/index_sw.py", line 75, in sw_index_spot
    r = requests.post(url, headers=sw_headers, data=payload)
  File "/aporchid08/lib/python3.7/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/aporchid08/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/aporchid08/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/aporchid08/lib/python3.7/site-packages/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/aporchid08/lib/python3.7/site-packages/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/aporchid08/lib/python3.7/site-packages/requests/sessions.py", line 192, in resolve_redirects
    f"Exceeded {self.max_redirects} redirects.", response=resp
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by jindaxiang** [comment]
> sw_index_spot

该接口暂时不能使用
