### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by realcyyy** [akfamily/akshare#3248]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本 3.9.12

3. AKShare 版本 1.8.18
4. 接口的名称和代码
    stock_zh_index_hist_csindex
   df = ak.stock_zh_index_hist_csindex(symbol='000832', start_date='2022-11-22', end_date='2022-11-23')
5. 接口报错的截图或代码
>>> import akshare as ak
>>> df = ak.stock_zh_index_hist_csindex(symbol='000832', start_date='2022-11-22', end_date='2022-11-23')
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'peg'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\anaconda\lib\site-packages\akshare\index\stock_zh_index_csindex.py", line 39, in stock_zh_index_hist_csindex
    del temp_df["peg"]
  File "D:\anaconda\lib\site-packages\pandas\core\generic.py", line 4048, in __delitem__
    loc = self.axes[-1].get_loc(key)
  File "D:\anaconda\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'peg'
6. 期望获得的正确结果
可以正常获取中证转债的数据

**Comment by jindaxiang** [comment]
> 4\. 000832

接口可以正常使用
