### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by zacharyzzc** [akfamily/akshare#3249]
描述遇到的问题
1. 操作系统版本 Mac12.5.1
2. Python 版本 3.8.0
3. AKShare 版本 1.8.18
4. 接口的名称和代码 stock_balance_sheet_by_yearly_em stock_balance_sheet_by_yearly_em_df = ak.stock_balance_sheet_by_yearly_em(symbol="SH601318")
5. 接口报错的截图或代码
Traceback (most recent call last):
  File "/Users/zack/work/Code/Py/akshareDemo/main.py", line 12, in <module>
    stock_balance_sheet_by_yearly_em_df = ak.stock_balance_sheet_by_yearly_em(symbol="SH601318")
  File "/Users/zack/work/Code/Py/akshareDemo/venv/lib/python3.8/site-packages/akshare/stock_feature/stock_three_report_em.py", line 90, in stock_balance_sheet_by_yearly_em
    temp_df = pd.DataFrame(data_json["data"])
KeyError: 'data' 
6. 期望获得的正确结果 可以正常获取数据

就这个股票有点问题，其它股票这个接口是正常的

**Comment by zacharyzzc** [comment]
就这个股票有点问题，其它股票这个接口是正常的

**Comment by jindaxiang** [comment]
> 4\. SH601318

感谢反馈问题；已修复该问题，升级到 AKShare 1.8.19 版本使用
