### ISSUE TITLE
AKShare 接口问题报告：当使用stock_zh_a_daily接口获取上证指数，行业等数据时，不存在amount_data_json导致报错

### ISSUE THREAD

**Issue by meislzhua** [akfamily/akshare#3273]
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/mnt/SSD-Other2/linux/workspace/py_ml/src/DL_Base/Data/StockDataForDB.py", line 616, in handle_loop
    h = self.handle_one_stock()
  File "/mnt/SSD-Other2/linux/workspace/py_ml/src/DL_Base/Data/StockDataForDB.py", line 459, in handle_one_stock
    self.handle_target_bourse(db_stock.bourse)
  File "/mnt/SSD-Other2/linux/workspace/py_ml/src/DL_Base/Data/StockDataForDB.py", line 434, in handle_target_bourse
    StockDataForDB.save_bourse_day_list(db_bourse)
  File "/mnt/SSD-Other2/linux/workspace/py_ml/src/DL_Base/Data/StockDataForDB.py", line 139, in save_bourse_day_list
    day_list = StockData.get_bourse_day_data(symbol=db_bourse.symbol)
  File "/mnt/SSD-Other2/linux/workspace/py_ml/src/DL_Base/Data/StockData.py", line 353, in get_bourse_day_data
    day_list = ak.stock_zh_a_daily(symbol=symbol, start_date=start_date, end_date=end_date)
  File "/home/meislzhua/.local/lib/python3.10/site-packages/akshare/stock/stock_zh_a_sina.py", line 189, in stock_zh_a_daily
    amount_data_json = demjson.decode(
  File "/home/meislzhua/.local/lib/python3.10/site-packages/akshare/utils/demjson.py", line 5740, in decode
    result = j.decode(txt,
  File "/home/meislzhua/.local/lib/python3.10/site-packages/akshare/utils/demjson.py", line 4957, in decode
    raise errors[0]
akshare.utils.demjson.JSONDecodeError: No value to decode

当使用stock_zh_a_daily接口获取上证指数，行业等数据时，不存在amount_data_json导致报错
例如sz399001

**Comment by jindaxiang** [comment]
> Process SpawnProcess-1: Traceback (most recent call last): File "/mnt/SSD-Other2/linux/workspace/py_ml/src/DL_Base/Data/StockDataForDB.py", line 616, in handle_loop h = self.handle_one_stock() File "/mnt/SSD-Other2/linux/workspace/py_ml/src/DL_Base/Data/StockDataForDB.py", line 459, in handle_one_stock self.handle_target_bourse(db_stock.bourse) File "/mnt/SSD-Other2/linux/workspace/py_ml/src/DL_Base/Data/StockDataForDB.py", line 434, in handle_target_bourse StockDataForDB.save_bourse_day_list(db_bourse) File "/mnt/SSD-Other2/linux/workspace/py_ml/src/DL_Base/Data/StockDataForDB.py", line 139, in save_bourse_day_list day_list = StockData.get_bourse_day_data(symbol=db_bourse.symbol) File "/mnt/SSD-Other2/linux/workspace/py_ml/src/DL_Base/Data/StockData.py", line 353, in get_bourse_day_data day_list = ak.stock_zh_a_daily(symbol=symbol, start_date=start_date, end_date=end_date) File "/home/meislzhua/.local/lib/python3.10/site-packages/akshare/stock/stock_zh_a_sina.py", line 189, in stock_zh_a_daily amount_data_json = demjson.decode( File "/home/meislzhua/.local/lib/python3.10/site-packages/akshare/utils/demjson.py", line 5740, in decode result = j.decode(txt, File "/home/meislzhua/.local/lib/python3.10/site-packages/akshare/utils/demjson.py", line 4957, in decode raise errors[0] akshare.utils.demjson.JSONDecodeError: No value to decode
> 
> 当使用stock_zh_a_daily接口获取上证指数，行业等数据时，不存在amount_data_json导致报错 例如sz399001

该接口只用来获取股票的数据；其他数据请用相应的接口
