### ISSUE TITLE
AKShare 接口问题报告 stock_hot_rank_em 失效

### ISSUE THREAD

**Issue by wukan1986** [akfamily/akshare#3304]
stock_hot_rank_em 接口失效

好像接口加密了

https://gbcdn.dfcfw.com/rank/popularityList.js?type=0&sort=0&page=1&v=2022_12_21_16_12

var popularityList='IxOR03dK218NE9Vmt3p7Ox+ ...

**Comment by jindaxiang** [comment]
> stock_hot_rank_em 接口失效
> 
> 好像接口加密了
> 
> https://gbcdn.dfcfw.com/rank/popularityList.js?type=0&sort=0&page=1&v=2022_12_21_16_12
> 
> var popularityList='IxOR03dK218NE9Vmt3p7Ox+ ...

接口可以正常使用

**Comment by wukan1986** [comment]
```python
Traceback (most recent call last):
  File "D:/Users/Kan/Documents/GitHub/ddump/examples/akshare/stock_hot.py", line 27, in <module>
    d.download(kw=[])
  File "D:\Users\Kan\Documents\GitHub\ddump\ddump\api\dump.py", line 146, in download
    self.df = api(*self.args, **_kwargs)
  File "D:\Users\Kan\miniconda3\envs\py38\lib\site-packages\akshare\stock\stock_hot_rank_em.py", line 27, in stock_hot_rank_em
    r = requests.post(url, json=payload)
  File "D:\Users\Kan\miniconda3\envs\py38\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\Users\Kan\miniconda3\envs\py38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Users\Kan\miniconda3\envs\py38\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Users\Kan\miniconda3\envs\py38\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Users\Kan\miniconda3\envs\py38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(10060, '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。', None, 10060, None))

```

**Comment by wukan1986** [comment]
懂了，我用的是1.8.32版

**Comment by wukan1986** [comment]
可惜，升级成1.8.33也不行
```python
  File "D:/Users/Kan/miniconda3/envs/py38/Lib/site-packages/akshare/stock/stock_hot_rank_em.py", line 195, in <module>
    stock_hot_rank_em_df = stock_hot_rank_em()
  File "D:/Users/Kan/miniconda3/envs/py38/Lib/site-packages/akshare/stock/stock_hot_rank_em.py", line 27, in stock_hot_rank_em
    r = requests.post(url, json=payload)
  File "D:\Users\Kan\miniconda3\envs\py38\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\Users\Kan\miniconda3\envs\py38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Users\Kan\miniconda3\envs\py38\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Users\Kan\miniconda3\envs\py38\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Users\Kan\miniconda3\envs\py38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))

```
