### ISSUE TITLE
Error when parsing WCI index 

### ISSUE THREAD

**Issue by ericwbzhang** [akfamily/akshare#3424]
**Describe the bug**
drewry_wci_index fail when parsing text 

**To Reproduce**

drewry_wci_index_df = ak.drewry_wci_index(symbol="composite")
Traceback (most recent call last):
  File xxxxxxxxx
    drewry_wci_index_df = ak.drewry_wci_index(symbol="composite")
  File "C:\xxxxx\lib\site-packages\akshare\index\drewry_index.py", line 38, in drewry_wci_index
    data_text = soup.find_all("script")[-5].string.strip("window.infographicData=")[:-1]
AttributeError: 'NoneType' object has no attribute 'strip'

**Desktop (please complete the following information):**
OS: Win10
python: 3.7.10

ak.__version__
Out[19]: '1.8.44'
requests.__version__
Out[23]: '2.25.1'
import bs4
bs4.__version__
Out[25]: '4.9.3'

**Comment by jindaxiang** [comment]
> **Describe the bug** drewry_wci_index fail when parsing text
> 
> **To Reproduce**
> 
> drewry_wci_index_df = ak.drewry_wci_index(symbol="composite") Traceback (most recent call last): File xxxxxxxxx drewry_wci_index_df = ak.drewry_wci_index(symbol="composite") File "C:\xxxxx\lib\site-packages\akshare\index\drewry_index.py", line 38, in drewry_wci_index data_text = soup.find_all("script")[-5].string.strip("window.infographicData=")[:-1] AttributeError: 'NoneType' object has no attribute 'strip'
> 
> **Desktop (please complete the following information):** OS: Win10 python: 3.7.10
> 
> ak.**version** Out[19]: '1.8.44' requests.**version** Out[23]: '2.25.1' import bs4 bs4.**version** Out[25]: '4.9.3'

感谢反馈问题；已修复该问题，升级到 AKShare 1.8.72 版本使用

**Comment by ericwbzhang** [comment]
ak.drewry_wci_index('composite') failed again. 

Python 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 8.4.0
Python 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)] on win32
import akshare as ak
wci= ak.drewry_wci_index('composite')
Traceback (most recent call last):
  File "C:\Users\ericw\anaconda3\envs\mktr\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-2b22852cc552>", line 1, in <cell line: 1>
    wci= ak.drewry_wci_index('composite')
  File "D:\akshare\akshare\index\drewry_index.py", line 43, in drewry_wci_index
    day = temp_df["date"].str.split("-", expand=True).iloc[:, 0].str.strip()
  File "C:\Users\ericw\anaconda3\envs\mktr\lib\site-packages\pandas\core\generic.py", line 5575, in __getattr__
    return object.__getattribute__(self, name)
  File "C:\Users\ericw\anaconda3\envs\mktr\lib\site-packages\pandas\core\accessor.py", line 182, in __get__
    accessor_obj = self._accessor(obj)
  File "C:\Users\ericw\anaconda3\envs\mktr\lib\site-packages\pandas\core\strings\accessor.py", line 177, in __init__
    self._inferred_dtype = self._validate(data)
  File "C:\Users\ericw\anaconda3\envs\mktr\lib\site-packages\pandas\core\strings\accessor.py", line 231, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!


ak.__version__
Out[4]: '1.9.3'
