### ISSUE TITLE
ak.stock_info_sh_name_code() 运行时产生错误

### ISSUE THREAD

**Issue by icespacelivecn** [akfamily/akshare#3469]
**Describe the bug**
ak.stock_info_sh_name_code() 运行时产生错误

**To Reproduce**
在python下运行：
```
import akshare as ak
stock_info_sh_name_code_df = ak.stock_info_sh_name_code(symbol="主板A股")
print(stock_info_sh_name_code_df)
```
报错：
```
>>> stock_info_sh_name_code_df = ak.stock_info_sh_name_code()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jason/.pyenv/versions/py38/lib/python3.8/site-packages/akshare/stock/stock_info.py", line 176, in stock_info_sh_name_code
    temp_df.columns = columns
  File "/Users/jason/.pyenv/versions/py38/lib/python3.8/site-packages/pandas/core/generic.py", line 5915, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/Users/jason/.pyenv/versions/py38/lib/python3.8/site-packages/pandas/core/generic.py", line 823, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/Users/jason/.pyenv/versions/py38/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 230, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/Users/jason/.pyenv/versions/py38/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 14 elements, new values have 13 elements
```

或者在aktools下调用url
http://127.0.0.1:8080/api/public/stock_info_sz_name_code

Internal Server Error

**Expected behavior**
返回正确的股票列表

**Screenshots**

**Desktop (please complete the following information):**
MacOS Monteray 16.2 Python 3.8

**Smartphone (please complete the following information):**

**Additional context**

**Comment by icespacelivecn** [comment]
AKShare version 1.8.59

**Comment by icespacelivecn** [comment]
Upgrade to the latest version resolved. Close the issue.
