### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by nianbingsihan** [akfamily/akshare#3470]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本:  macOS 12.6.1 Montery (21G217)
2. Python 版本:  3.10.8
3. AKShare 版本:  1.8.84
4. 接口的名称和代码: ak.stock_info_sh_delist() 查询暂停/终止上市-上证
```
print(ak.stock_info_sh_delist())
```
6. 接口报错的截图或代码: 
```
Traceback (most recent call last):
  File "/Users/admin/Workspaces/PyCharm/test/AKshareTest.py", line 12, in <module>
    print(ak.stock_info_sh_delist())
  File "/Users/admin/Workspaces/PyCharm/test/venv/lib/python3.10/site-packages/akshare/stock/stock_info.py", line 324, in stock_info_sh_delist
    temp_df.columns = [
  File "/Users/admin/Workspaces/PyCharm/test/venv/lib/python3.10/site-packages/pandas/core/generic.py", line 5915, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/Users/admin/Workspaces/PyCharm/test/venv/lib/python3.10/site-packages/pandas/core/generic.py", line 823, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/Users/admin/Workspaces/PyCharm/test/venv/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 227, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/Users/admin/Workspaces/PyCharm/test/venv/lib/python3.10/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 14 elements, new values have 13 elements
```

8. 期望获得的正确结果 上证交易所暂停/终止上市股票集合

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本:  macOS 12.6.1 Montery (21G217)
> 2. Python 版本:  3.10.8
> 3. AKShare 版本:  1.8.84
> 4. 接口的名称和代码: ak.stock_info_sh_delist() 查询暂停/终止上市-上证
> 
> ```
> print(ak.stock_info_sh_delist())
> ```
> 
> 6. 接口报错的截图或代码:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/admin/Workspaces/PyCharm/test/AKshareTest.py", line 12, in <module>
>     print(ak.stock_info_sh_delist())
>   File "/Users/admin/Workspaces/PyCharm/test/venv/lib/python3.10/site-packages/akshare/stock/stock_info.py", line 324, in stock_info_sh_delist
>     temp_df.columns = [
>   File "/Users/admin/Workspaces/PyCharm/test/venv/lib/python3.10/site-packages/pandas/core/generic.py", line 5915, in __setattr__
>     return object.__setattr__(self, name, value)
>   File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
>   File "/Users/admin/Workspaces/PyCharm/test/venv/lib/python3.10/site-packages/pandas/core/generic.py", line 823, in _set_axis
>     self._mgr.set_axis(axis, labels)
>   File "/Users/admin/Workspaces/PyCharm/test/venv/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 227, in set_axis
>     self._validate_set_axis(axis, new_labels)
>   File "/Users/admin/Workspaces/PyCharm/test/venv/lib/python3.10/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
>     raise ValueError(
> ValueError: Length mismatch: Expected axis has 14 elements, new values have 13 elements
> ```
> 
> 8. 期望获得的正确结果 上证交易所暂停/终止上市股票集合

感谢反馈问题，已修复该问题，升级到 AKShare 1.8.86 版本使用
