### ISSUE TITLE
AKShare 接口问题报告 stock_info_sz_delist(symbol="暂停上市公司")  KeyError: '终止上市日期'

### ISSUE THREAD

**Issue by nianbingsihan** [akfamily/akshare#3506]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本:  macOS 12.6.1 Montery (21G217)
2. Python 版本: 3.10.8
3. AKShare 版本: 1.8.96
4. 接口的名称和代码: 
```
print("AKShare version = " + ak.__version__)
stock_info_sz_delist_df = ak.stock_info_sz_delist(symbol="暂停上市公司")
print(stock_info_sz_delist_df)
```

5. 接口报错的截图或代码:
```
AKShare version = 1.8.96
Traceback (most recent call last):
  File "/Users/admin/Workspaces/PyCharm/test/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3803, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '终止上市日期'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/admin/Workspaces/PyCharm/test/AKshareTest.py", line 21, in <module>
    stock_info_sz_delist_df = ak.stock_info_sz_delist(symbol="暂停上市公司")
  File "/Users/admin/Workspaces/PyCharm/test/venv/lib/python3.10/site-packages/akshare/stock/stock_info.py", line 346, in stock_info_sz_delist
    temp_df['终止上市日期'] = pd.to_datetime(temp_df['终止上市日期']).dt.date
  File "/Users/admin/Workspaces/PyCharm/test/venv/lib/python3.10/site-packages/pandas/core/frame.py", line 3804, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/admin/Workspaces/PyCharm/test/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    raise KeyError(key) from err
KeyError: '终止上市日期'
```

6. 期望获得的正确结果：深交所暂停上市公司原始接口返回空数据时，stock_info_sz_delist(symbol="暂停上市公司")接口应返回空数据[]

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本:  macOS 12.6.1 Montery (21G217)
> 2. Python 版本: 3.10.8
> 3. AKShare 版本: 1.8.96
> 4. 接口的名称和代码:
> 
> ```
> print("AKShare version = " + ak.__version__)
> stock_info_sz_delist_df = ak.stock_info_sz_delist(symbol="暂停上市公司")
> print(stock_info_sz_delist_df)
> ```
> 
> 5. 接口报错的截图或代码:
> 
> ```
> AKShare version = 1.8.96
> Traceback (most recent call last):
>   File "/Users/admin/Workspaces/PyCharm/test/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3803, in get_loc
>     return self._engine.get_loc(casted_key)
>   File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: '终止上市日期'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/admin/Workspaces/PyCharm/test/AKshareTest.py", line 21, in <module>
>     stock_info_sz_delist_df = ak.stock_info_sz_delist(symbol="暂停上市公司")
>   File "/Users/admin/Workspaces/PyCharm/test/venv/lib/python3.10/site-packages/akshare/stock/stock_info.py", line 346, in stock_info_sz_delist
>     temp_df['终止上市日期'] = pd.to_datetime(temp_df['终止上市日期']).dt.date
>   File "/Users/admin/Workspaces/PyCharm/test/venv/lib/python3.10/site-packages/pandas/core/frame.py", line 3804, in __getitem__
>     indexer = self.columns.get_loc(key)
>   File "/Users/admin/Workspaces/PyCharm/test/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
>     raise KeyError(key) from err
> KeyError: '终止上市日期'
> ```
> 
> 6. 期望获得的正确结果：深交所暂停上市公司原始接口返回空数据时，stock_info_sz_delist(symbol="暂停上市公司")接口应返回空数据[]

感谢反馈问题；已修复该问题，返回空 pandas.DataFrame，升级到 AKShare 1.8.98 使用
