### ISSUE TITLE
AKShare 接口问题报告: 无法得到可转债数据

### ISSUE THREAD

**Issue by Shilee78** [akfamily/akshare#3540]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
4. 接口的名称和代码
5. 接口报错的截图或代码
6. 期望获得的正确结果

我的代码如下：
----------------------------------
import numpy as np
import pandas as pd

import akshare as ak

bond_zh_cov_df = ak.bond_zh_cov()
------------------------------------------

我得到的报错信息：
-----------------------------------------------
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/D/dev/py/invest/convertbond/convertbondinfo.py", line 9, in <module>
    bond_zh_cov_df = ak.bond_zh_cov()
  File "C:\Users\dell\AppData\Roaming\Python\Python36\site-packages\akshare\bond\zh_bond_cov_sina.py", line 106, in bond_zh_cov
    r = requests.get(url, params=params)
  File "C:\Users\dell\AppData\Roaming\Python\Python36\site-packages\requests\api.py", line 75, in get
---------------------------------------------

我查了下zh_bond_cov_sina.py的 bond_zh_cov()函数，看到如下信息：
-------------------------------------------------
def bond_zh_cov():
    """
    东方财富网-数据中心-新股数据-可转债数据
    http://data.eastmoney.com/kzz/default.html
    :return: 可转债数据
    :rtype: pandas.DataFrame
    """
    url = "http://dcfm.eastmoney.com/em_mutisvcexpandinterface/api/js/get"
    params = {
        "type": "KZZ_LB2.0",
        "token": "70f12f2f4f091e459a279469fe49eca5",
        "cmd": "",
        "st": "STARTDATE",
        "sr": "-1",
        "p": "1",
        "ps": "5000",
        "js": "var {jsname}={pages:(tp),data:(x),font:(font)}",
    }
    r = requests.get(url, params=params)
    text_data = r.text
    json_data = demjson.decode(text_data[text_data.find("=") + 1 :])
    temp_df = pd.DataFrame(json_data["data"])

看起来东方财富不让爬数据了吗？

**Comment by jindaxiang** [comment]
> bond_zh_cov

可以正常获取
