### ISSUE TITLE
stock_hold_control_cninfo接口问题

### ISSUE THREAD

**Issue by wg142857** [akfamily/akshare#3816]

**Comment by wg142857** [comment]
> stock_hold_control_cninfo接口好像还是不能用, 希望尽快修复

版本:
akshare 1.9.81
官网代码:
import akshare as ak
stock_hold_control_cninfo_df = ak.stock_hold_control_cninfo(symbol="全部")
print(stock_hold_control_cninfo_df)
报错信息:
Traceback (most recent call last):
File "D:\app\spiders\测试.py", line 3, in
stock_hold_control_cninfo_df = ak.stock_hold_control_cninfo(symbol="全部")
File "F:\AnacondaEXE\envs\py_STOCK\lib\site-packages\akshare\stock\stock_hold_control_cninfo.py", line 90, in stock_hold_control_cninfo
temp_df = pd.DataFrame(data_json["records"])
KeyError: 'records'

**Comment by wg142857** [comment]
> stock_hold_control_cninfo接口好像还是不能用, 希望尽快修复
