### ISSUE TITLE
AKShare index_stock_hist 接口问题报告

### ISSUE THREAD

**Issue by liyue2008** [akfamily/akshare#3910]
**描述遇到的问题**

执行如下示例代码：

```python
import akshare as ak

if __name__ == '__main__':

    stock_index_hist_df = ak.index_stock_hist()
    print(stock_index_hist_df)
```

报错如下：

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/user/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/user/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module
    run_module_as_main(options.target, alter_argv=True)
  File "/home/user/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/user/workspace/quants/strategy/portfolio/test.py", line 5, in <module>
    stock_index_hist_df = ak.index_stock_hist()
  File "/home/user/.virtualenvs/quants/lib/python3.10/site-packages/akshare/index/index_cons.py", line 190, in index_stock_hist
    last_page_num = soup.find_all("a", attrs={"target": "_self"})[-2].text
IndexError: list index out of range
```

1. 操作系统版本: ubuntu 22.04
2. Python 版本: Python 3.10.6
4. AKShare 版本: akshare-1.10.35
5. 接口的名称和代码: index_stock_hist
6. 接口报错的截图或代码 : 如上
7. 期望获得的正确结果: 返回正确的数据

**Comment by albertandking** [comment]
> **描述遇到的问题**
> 
> 执行如下示例代码：
> 
> ```python
> import akshare as ak
> 
> if __name__ == '__main__':
> 
>     stock_index_hist_df = ak.index_stock_hist()
>     print(stock_index_hist_df)
> ```
> 
> 报错如下：
> 
> ```shell
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/home/user/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
>     cli.main()
>   File "/home/user/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
>     run()
>   File "/home/user/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module
>     run_module_as_main(options.target, alter_argv=True)
>   File "/home/user/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/user/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
>     exec(code, run_globals)
>   File "/home/user/workspace/quants/strategy/portfolio/test.py", line 5, in <module>
>     stock_index_hist_df = ak.index_stock_hist()
>   File "/home/user/.virtualenvs/quants/lib/python3.10/site-packages/akshare/index/index_cons.py", line 190, in index_stock_hist
>     last_page_num = soup.find_all("a", attrs={"target": "_self"})[-2].text
> IndexError: list index out of range
> ```
> 
> 1. 操作系统版本: ubuntu 22.04
> 2. Python 版本: Python 3.10.6
> 3. AKShare 版本: akshare-1.10.35
> 4. 接口的名称和代码: index_stock_hist
> 5. 接口报错的截图或代码 : 如上
> 6. 期望获得的正确结果: 返回正确的数据

感谢反馈问题；数据源未提供数据，已删除该接口

**Comment by jukxi** [comment]
请问大佬还有机会加回来这个接口吗。。。
