### ISSUE TITLE
AKShare 功能咨询

### ISSUE THREAD

**Issue by simon-yanghl** [akfamily/akshare#4018]
**描述遇到的问题**
1. 操作系统版本
WIN11
2. Python 版本
3.11
3. AKShare 版本
最新，提问前更新

想把py程序做成exe方便使用，打包程序后运行出错
Traceback (most recent call last):
  File "五线合一自动运行版v1.0.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "akshare\__init__.py", line 4793, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "akshare\futures\futures_basis.py", line 27, in <module>
  File "akshare\futures\cons.py", line 501, in get_calendar
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kenan\\AppData\\Local\\Temp\\_MEI448642\\akshare\\file_fold\\calendar.json'
[40784] Failed to execute script '五线合一自动运行版v1.0' due to unhandled exception!

咨询chatgpt和自行研究后说是cons.py中的get_jason_path函数没有检查程序是否被打包，从而不能选择从哪个目录读取json文件，请问是否可以进行相应改进？

**Comment by albertandking** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    WIN11
> 2. Python 版本
>    3.11
> 3. AKShare 版本
>    最新，提问前更新
> 
> 想把py程序做成exe方便使用，打包程序后运行出错 Traceback (most recent call last): File "五线合一自动运行版v1.0.py", line 15, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module File "akshare__init__.py", line 4793, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module File "akshare\futures\futures_basis.py", line 27, in File "akshare\futures\cons.py", line 501, in get_calendar FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\kenan\AppData\Local\Temp\_MEI448642\akshare\file_fold\calendar.json' [40784] Failed to execute script '五线合一自动运行版v1.0' due to unhandled exception!
> 
> 咨询chatgpt和自行研究后说是cons.py中的get_jason_path函数没有检查程序是否被打包，从而不能选择从哪个目录读取json文件，请问是否可以进行相应改进？

需要在你本地代码包含相应的目录
