### ISSUE TITLE
stock_info_bj_name_code calls getting blocked by BSE website

### ISSUE THREAD

**Issue by hy-lei** [akfamily/akshare#4073]
Potentially because the website uses session cookies.  Replacing requests.post calls with session.post resolves the issue (#4074)

[2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO -   File "/Users/.../get_avail_sec_sym.py", line 41, in <module>
[2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO -     df_bjse = ak.stock_info_bj_name_code()
[2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO -   File "/Users/.../lib/python3.10/site-packages/akshare/stock/stock_info.py", line 206, in stock_info_bj_name_code
[2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO -     data_json = json.loads(data_text[data_text.find("[") : -1])
[2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO -   File "/Users/.../lib/python3.10/json/__init__.py", line 346, in loads
[2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO -     return _default_decoder.decode(s)
[2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO -   File "/Users/.../lib/python3.10/json/decoder.py", line 337, in decode
[2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO -     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO -   File "/Users/.../lib/python3.10/json/decoder.py", line 355, in raw_decode
[2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO -     raise JSONDecodeError("Expecting value", s, err.value) from None
[2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO - json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)

**Comment by albertandking** [comment]
> Potentially because the website uses session cookies. Replacing requests.post calls with session.post resolves the issue (#4074)
> 
> [2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO - Traceback (most recent call last): [2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO - File "/Users/.../get_avail_sec_sym.py", line 41, in [2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO - df_bjse = ak.stock_info_bj_name_code() [2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO - File "/Users/.../lib/python3.10/site-packages/akshare/stock/stock_info.py", line 206, in stock_info_bj_name_code [2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO - data_json = json.loads(data_text[data_text.find("[") : -1]) [2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO - File "/Users/.../lib/python3.10/json/**init**.py", line 346, in loads [2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO - return _default_decoder.decode(s) [2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO - File "/Users/.../lib/python3.10/json/decoder.py", line 337, in decode [2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO - obj, end = self.raw_decode(s, idx=_w(s, 0).end()) [2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO - File "/Users/.../lib/python3.10/json/decoder.py", line 355, in raw_decode [2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO - raise JSONDecodeError("Expecting value", s, err.value) from None [2023-08-21, 23:06:18 EDT] {subprocess.py:93} INFO - json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)

接口测试正常
