### ISSUE TITLE
AKShare 接口问题报告(fund_etf_hist_min_em)

### ISSUE THREAD

**Issue by kid143** [akfamily/akshare#4234]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本windows 10 22H2
2. Python 版本 3.10
3. AKShare 版本 1.11.56
4. 接口的名称和代码
  fund_etf_hist_min_em, 东方财富-ETF 行情
6. 接口报错的截图或代码
```
Traceback (most recent call last):
  File "C:\Users\boris\Documents\codes\financedata\etf_kline_downloader.py", line 265, in <module>
    etf()
  File "C:\Users\boris\scoop\apps\miniconda3\current\envs\financedata\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\boris\scoop\apps\miniconda3\current\envs\financedata\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\boris\scoop\apps\miniconda3\current\envs\financedata\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\boris\scoop\apps\miniconda3\current\envs\financedata\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\boris\scoop\apps\miniconda3\current\envs\financedata\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\boris\Documents\codes\financedata\etf_kline_downloader.py", line 234, in update_kline
    data = ak.fund_etf_hist_min_em(
  File "C:\Users\boris\scoop\apps\miniconda3\current\envs\financedata\lib\site-packages\akshare\fund\fund_etf_em.py", line 279, in fund_etf_hist_min_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '159789'
```
经调查，应该是该ETF基金近期已经清盘，因此内部接口 _fund_etf_code_id_map_em()返回的map不再包含该代码

8. 期望获得的正确结果
期望行情接口返回空的结果集或者给出更明确的错误信息

**Comment by albertandking** [comment]
> 4\. fund_etf_hist_min_em

用户端自行判断更为合适
