### ISSUE TITLE
ak.futures_zh_minute_sina(symbol="RB2401", period="5")

### ISSUE THREAD

**Issue by hui-cao778** [akfamily/akshare#4235]
获取数据总是报错，前几天都正常。
>>> ak.futures_zh_minute_sina(symbol="SC2401", period="60")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\site-packages\akshare\futures\futures_zh_sina.py", line 614, in futures_zh_minute_sina
    temp_df = pd.DataFrame(json.loads(r.text.split("=(")[1].split(");")[0]))
IndexError: list index out of range
6. 期望获得的正确结果

**Comment by albertandking** [comment]
> SC2401

接口测试正常，注意访问频率
