### ISSUE TITLE
AKShare 接口问题报告 stock_zh_a_daily的两个问题

### ISSUE THREAD

**Issue by sparkwj** [akfamily/akshare#4237]
Python 3.10.10 (main, Mar 21 2023, 13:41:39) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import akshare as ak
>>> ak.stock_zh_a_daily(symbol="sz300136", start_date="19910403", end_date="20231027", adjust="qfq")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/spark/anaconda3/envs/dt/lib/python3.10/site-packages/akshare/stock/stock_zh_a_sina.py", line 215, in stock_zh_a_daily
    temp_df.columns = [
  File "/Users/spark/anaconda3/envs/dt/lib/python3.10/site-packages/pandas/core/generic.py", line 6218, in __setattr__
    return object.__setattr__(self, name, value)
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/Users/spark/anaconda3/envs/dt/lib/python3.10/site-packages/pandas/core/generic.py", line 767, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/Users/spark/anaconda3/envs/dt/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 227, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/Users/spark/anaconda3/envs/dt/lib/python3.10/site-packages/pandas/core/internals/base.py", line 85, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 10 elements, new values have 8 elements

>>> ak.stock_zh_a_daily(symbol="sz002411", start_date="19910403", end_date="20231027", adjust="qfq")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/spark/anaconda3/envs/dt/lib/python3.10/site-packages/akshare/stock/stock_zh_a_sina.py", line 193, in stock_zh_a_daily
    amount_data_json = demjson.decode(
  File "/Users/spark/anaconda3/envs/dt/lib/python3.10/site-packages/akshare/utils/demjson.py", line 5740, in decode
    result = j.decode(txt,
  File "/Users/spark/anaconda3/envs/dt/lib/python3.10/site-packages/akshare/utils/demjson.py", line 4957, in decode
    raise errors[0]
akshare.utils.demjson.JSONDecodeError: No value to decode

>>> ak.__version__
'1.11.56'

**Comment by albertandking** [comment]
> Python 3.10.10 (main, Mar 21 2023, 13:41:39) [Clang 14.0.6 ] on darwin Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import akshare as ak
> > > > ak.stock_zh_a_daily(symbol="sz300136", start_date="19910403", end_date="20231027", adjust="qfq")
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/Users/spark/anaconda3/envs/dt/lib/python3.10/site-packages/akshare/stock/stock_zh_a_sina.py", line 215, in stock_zh_a_daily
> > > > temp_df.columns = [
> > > > File "/Users/spark/anaconda3/envs/dt/lib/python3.10/site-packages/pandas/core/generic.py", line 6218, in **setattr**
> > > > return object.**setattr**(self, name, value)
> > > > File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.**set**
> > > > File "/Users/spark/anaconda3/envs/dt/lib/python3.10/site-packages/pandas/core/generic.py", line 767, in _set_axis
> > > > self._mgr.set_axis(axis, labels)
> > > > File "/Users/spark/anaconda3/envs/dt/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 227, in set_axis
> > > > self._validate_set_axis(axis, new_labels)
> > > > File "/Users/spark/anaconda3/envs/dt/lib/python3.10/site-packages/pandas/core/internals/base.py", line 85, in _validate_set_axis
> > > > raise ValueError(
> > > > ValueError: Length mismatch: Expected axis has 10 elements, new values have 8 elements
> 
> > > > ak.stock_zh_a_daily(symbol="sz002411", start_date="19910403", end_date="20231027", adjust="qfq")
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/Users/spark/anaconda3/envs/dt/lib/python3.10/site-packages/akshare/stock/stock_zh_a_sina.py", line 193, in stock_zh_a_daily
> > > > amount_data_json = demjson.decode(
> > > > File "/Users/spark/anaconda3/envs/dt/lib/python3.10/site-packages/akshare/utils/demjson.py", line 5740, in decode
> > > > result = j.decode(txt,
> > > > File "/Users/spark/anaconda3/envs/dt/lib/python3.10/site-packages/akshare/utils/demjson.py", line 4957, in decode
> > > > raise errors[0]
> > > > akshare.utils.demjson.JSONDecodeError: No value to decode
> 
> > > > ak.**version**
> > > > '1.11.56'

注意访问频率，降低访问频率后应该可以恢复

**Comment by sparkwj** [comment]
不是频率问题，是某些股票代码会出现问题，比如上面的两个股票代码，错误信息也不同的
