### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by mickey3721** [akfamily/akshare#4242]
windows11
python3.12
akshare 1.11.58

Traceback (most recent call last):
  File "D:\PythonPjt\PythonTdx\Akshare\GetData.py", line 11, in <module>
    import akshare as ak
  File "C:\Users\micke\AppData\Roaming\Python\Python312\site-packages\akshare\__init__.py", line 3978, in <module>
    from akshare.stock_feature.stock_a_pe_and_pb import (
  File "C:\Users\micke\AppData\Roaming\Python\Python312\site-packages\akshare\stock_feature\stock_a_pe_and_pb.py", line 319, in <module>
    js_functions = py_mini_racer.MiniRacer()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micke\AppData\Roaming\Python\Python312\site-packages\py_mini_racer\py_mini_racer.py", line 185, in __init__
    self.__class__.ext = _build_ext_handle()
                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micke\AppData\Roaming\Python\Python312\site-packages\py_mini_racer\py_mini_racer.py", line 132, in _build_ext_handle
    raise RuntimeError("Native library not available at {}".format(EXTENSION_PATH))
RuntimeError: Native library not available at C:\Users\micke\AppData\Roaming\Python\Python312\site-packages\py_mini_racer\mini_racer.dll
Exception ignored in: <function MiniRacer.__del__ at 0x000002A613D4B6A0>
Traceback (most recent call last):
  File "C:\Users\micke\AppData\Roaming\Python\Python312\site-packages\py_mini_racer\py_mini_racer.py", line 322, in __del__
    self.ext.mr_free_context(getattr(self, "ctx", None))
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'mr_free_context'

在python3.11中，升级akshare1.11.58后问题相同

**Comment by mickey3721** [comment]
for the problem is python is not installed by default path,
copy mini_racer.dll from python installed path to C:\Users\micke\AppData\Roaming\Python\Python312\site-packages\py_mini_racer\
and the problem will be solved

**Comment by XstormLeigh** [comment]
no it's not working, my miniconda3 env doesn't even have a Python311 folder when it's created under C:\Users.
