### ISSUE TITLE
bond_china_close_return()报错

### ISSUE THREAD

**Issue by LittleWorm1** [akfamily/akshare#4243]
python：3.11.6
akshare：1.11.58

import akshare as ak
ak.bond_china_close_return(symbol="国债", period="1", start_date="20231101", end_date="20231101")

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\akshare\bond\bond_china_money.py", line 87, in bond_china_close_return
    data_json = r.json()
                ^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by albertandking** [comment]
> bond_china_close_return

经测试发现确实有访问不稳定的情况，可以在本地通过 try excetp 处理

**Comment by LittleWorm1** [comment]
无论try excetp多少次都是返回这个错误，不是不稳定的情况。
@albertandking
