### ISSUE TITLE
RuntimeError: Native library not available at *\mini_racer.dll

### ISSUE THREAD

**Issue by Timothy1101** [akfamily/akshare#4244]
When run Pyinstaller to convert Python program to exe file，if python program imports akshare, exe file can not run successfly with error:

C:\PythonProjects\pythonProject\pyinstall_test\dist>main.exe
Traceback (most recent call last):
  File "main.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "akshare\__init__.py", line 3759, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "akshare\stock_feature\stock_a_pe_and_pb.py", line 319, in <module>
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\Timothy\AppData\Local\Temp\_MEI307282\mini_racer.dll
[24532] Failed to execute script 'main' due to unhandled exception!
Exception ignored in: <function MiniRacer.__del__ at 0x0000017E71A1BA30>
Traceback (most recent call last):
  File "py_mini_racer\py_mini_racer.py", line 315, in __del__
AttributeError: 'NoneType' object has no attribute 'mr_free_context'

there is same issue in PyMiniRacer page
https://github.com/sqreen/PyMiniRacer/issues/143

but it looks there is no solution

**Comment by albertandking** [comment]
> When run Pyinstaller to convert Python program to exe file，if python program imports akshare, exe file can not run successfly with error:
> 
> C:\PythonProjects\pythonProject\pyinstall_test\dist>main.exe Traceback (most recent call last): File "main.py", line 7, in File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module File "akshare__init__.py", line 3759, in File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module File "akshare\stock_feature\stock_a_pe_and_pb.py", line 319, in File "py_mini_racer\py_mini_racer.py", line 178, in **init** File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle RuntimeError: Native library not available at C:\Users\Timothy\AppData\Local\Temp_MEI307282\mini_racer.dll [24532] Failed to execute script 'main' due to unhandled exception! Exception ignored in: <function MiniRacer.**del** at 0x0000017E71A1BA30> Traceback (most recent call last): File "py_mini_racer\py_mini_racer.py", line 315, in **del** AttributeError: 'NoneType' object has no attribute 'mr_free_context'
> 
> there is same issue in PyMiniRacer page [sqreen/PyMiniRacer#143](https://github.com/sqreen/PyMiniRacer/issues/143)
> 
> but it looks there is no solution

参考：https://blog.csdn.net/u013073518/article/details/130353145
