### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Junchao-Mellanox** [akfamily/akshare#4255]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 
MAC monterey 12.6.3
2. Python 版本
`3.10.11`
3. AKShare 版本
`1.11.62`
4. 接口的名称和代码
stock_hot_keyword_em
```python
import akshare as ak
df = ak.stock_hot_keyword_em(symbol='000001')
``` 
7. 接口报错的截图或代码
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/akshare/stock/stock_hot_rank_em.py", line 143, in stock_hot_keyword_em
    del temp_df["flag"]
  File "/usr/local/lib/python3.10/site-packages/pandas/core/generic.py", line 4441, in __delitem__
    loc = self.axes[-1].get_loc(key)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 418, in get_loc
    raise KeyError(key)
KeyError: 'flag'
```
9. 期望获得的正确结果
没有错误并且接口能正确返回数据

**Comment by albertandking** [comment]
> ```python
> stock_hot_keyword_em
> ```

接口正常；按文档说明使用
