### ISSUE TITLE
AKShare 接口问题报告 - 特定公司无法获取主营构成数据

### ISSUE THREAD

**Issue by Yunlong-He** [akfamily/akshare#4297]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
ubuntu-22.04
3. Python 版本
python-3.11
4. AKShare 版本
最新版本。

5. 接口报错的截图或代码
Traceback (most recent call last):
  File "/home/ubuntu/zygc/get_data.py", line 62, in <module>
    test()
  File "/home/ubuntu/zygc/get_data.py", line 55, in test
    df = ak.stock_zygc_em(symbol='sh600901')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tools/akshare/akshare/stock_fundamental/stock_zygc.py", line 100, in stock_zygc_em
    temp_df = temp_df[
              ^^^^^^^^
  File "/home/ubuntu/bin/anaconda3/envs/fintech/lib/python3.11/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/bin/anaconda3/envs/fintech/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6114, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/ubuntu/bin/anaconda3/envs/fintech/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6178, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['主营成本', '成本比例', '主营利润', '利润比例', '毛利率'] not in index"

7. 期望获得的正确结果

**Comment by albertandking** [comment]
> 4\. stock_zygc

目前接口正常
