### ISSUE TITLE
港股估值指标 异常

### ISSUE THREAD

**Issue by miabyss** [akfamily/akshare#4331]
```
Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import akshare as ak
>>>
>>> stock_hk_valuation_baidu_df = ak.stock_hk_valuation_baidu(symbol="02358", indicator="总市值", period="近一年")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\akshare\stock_feature\stock_hk_valuation_baidu.py", line 43, in stock_hk_valuation_baidu
    temp_df = pd.DataFrame(data_json["Result"]["chartInfo"][0]["body"])
TypeError: list indices must be integers or slices, not str
```

**描述遇到的问题**
1. 操作系统版本: Windows 10 专业版 x64 (10.0.19045 Build 19045)
2. Python 版本: 3.9.10
3. AKShare 版本: 1.11.89
4. 接口的名称和代码: 见上文
5. 接口报错的截图或代码: 见上文
6. 期望获得的正确结果: 运行无异常，或从官网移除过时的接口描述

**Comment by albertandking** [comment]
> 近一年

接口测试正常
