### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by zzzzzzz1049** [akfamily/akshare#4354]
Python=3.10.11 
AKShare=1.11.98

stock_news_em()函数运行时报错，使用默认参数也会报错

报错信息：

Traceback (most recent call last):
  File "C:\Users\a1605\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\a1605\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\a1605\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\a1605\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\a1605\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\a1605\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\a1605\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\a1605\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\a1605\Desktop\yiyan_plugin_demo\finchat_server.py", line 86, in get_company_fund_detail
    "news": get_company_news(company_code),
  File "C:\Users\a1605\Desktop\yiyan_plugin_demo\information.py", line 128, in get_company_news
    stock_news_em_df = ak.stock_news_em()
  File "C:\Users\a1605\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\akshare\news\news_stock.py", line 36, in stock_news_em
    temp_df = pd.DataFrame(data_json["result"]["cmsArticleWebOld"])
KeyError: 'cmsArticleWebOld'

**Comment by albertandking** [comment]
> stock_news_em

接口测试正常

**Comment by boyuZh** [comment]
我这边测试接口在mac上正常，但是windows就会报同样的错。

**Comment by boyuZh** [comment]
返回的json内容为：{'bizCode': '', 'bizMsg': '', 'code': 0, 'extra': {}, 'hitsTotal': 1, 'msg': 'OK', 'result': {'passportWeb': [{'uid': '8223456637392854', 'stockFollowerCount': 7289, 'alias': '<em>达利食品</em>', 'postCount': 0, 'fansCount': 0, 'portrait': 'https://avator.eastmoney.com/qface/8223456637392854/180', 'url': 'http://iguba.eastmoney.com/8223456637392854', 'introduction': ' ', 'userFollowingCount': 0, 'userSelectStockCount': 0}]}, 'searchId': 'b93a1e15-8497-4b4c-a4c8-744305b6f2d8'}
