### ISSUE TITLE
最新版本，index_fear_greed_funddb()接口报错

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#4769]
最新版本V1.13.40，index_fear_greed_funddb()接口报错：
_get_file_content_ths()函数中 file_data = f.read()报错：
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 208481: illegal multibyte sequence

**Comment by lem0ke** [comment]
同样存在该问题，我的报错：
Traceback (most recent call last):
  File "D:\test.py", line 33, in <module>
    index_fear_greed_funddb_df = ak.index_fear_greed_funddb(symbol="上证指数")
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\akshare\index\index_fear_greed_funddb.py", line 56, in index_fear_greed_funddb
    mcode = js_code.call("my_decode", data_json)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\py_mini_racer\py_mini_racer.py", line 271, in call
    return self.execute(js, timeout=timeout, max_memory=max_memory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\py_mini_racer\py_mini_racer.py", line 242, in execute
    ret = self.eval(wrapped_expr, timeout=timeout, max_memory=max_memory)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\py_mini_racer\py_mini_racer.py", line 228, in eval
    return MiniRacerValue(self, res).to_python()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\py_mini_racer\py_mini_racer.py", line 410, in to_python
    self._raise_from_error()
  File "C:\anaconda3\Lib\site-packages\py_mini_racer\py_mini_racer.py", line 401, in _raise_from_error
    raise JSEvalException(msg.decode('utf-8', errors='replace'))
py_mini_racer.py_mini_racer.JSEvalException: Uncaught Error: Malformed UTF-8 data at undefined:479:20
Error: Malformed UTF-8 data
    at Object.stringify (<anonymous>:479:27)
    at WordArray.init.toString (<anonymous>:216:41)
    at my_decode (<anonymous>:6000:22)
    at <anonymous>:1:46
    at <anonymous>:1:20974

**Comment by albertandking** [comment]
> 最新版本V1.13.40，index_fear_greed_funddb()接口报错： _get_file_content_ths()函数中 file_data = f.read()报错： UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 208481: illegal multibyte sequence

已修复，升级到 AKShare 1.13.40 使用

**Comment by lilaboc** [comment]
windows下默认编码是gbk, 仍然会报错, 需要把 index_fear_greed_funddb.py 的27行打开文件的时候加上 encoding="utf-8"

**Comment by lem0ke** [comment]
> windows下默认编码是gbk, 仍然会报错, 需要把 index_fear_greed_funddb.py 的27行打开文件的时候加上 encoding="utf-8"

确实存在该问题，按你说的方法修复后正常。麻烦作者更新一下 @albertandking

**Comment by albertandking** [comment]
> > windows下默认编码是gbk, 仍然会报错, 需要把 index_fear_greed_funddb.py 的27行打开文件的时候加上 encoding="utf-8"
> 
> 确实存在该问题，按你说的方法修复后正常。麻烦作者更新一下 @albertandking

已修复，升级到 AKShare 1.13.42 使用
