### ISSUE TITLE
AKShare 接口问题报告 （stock_zt_pool_em）

### ISSUE THREAD

**Issue by hua060097** [akfamily/akshare#4781]
akshare版本：1.13.46
python3版本：3.8.0
系统：macos 12.5
接口名：stock_zt_pool_em
代码：
import akshare as ak
import pandas as pd

stock_zt_pool_em_df = ak.stock_zt_pool_em(date='20210525')
print(stock_zt_pool_em_df)

报错：

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/akshare/__init__.py:2779: UserWarning: 为了支持更多特性，请将 Python 升级到 3.9.0 及以上版本！
  warnings.warn(
Traceback (most recent call last):
  File "/Users/momo/Documents/stockak2.py", line 4, in <module>
    stock_zt_pool_em_df = ak.stock_zt_pool_em(date='20210525')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/akshare/stock_feature/stock_ztb_em.py", line 50, in stock_zt_pool_em
    temp_df.columns = [
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 1 elements, new values have 17 elements

**Comment by hua060097** [comment]
3.9也试了，一样的报错：
Traceback (most recent call last):
  File "/Users/momo/Documents/stockak2.py", line 4, in <module>
    stock_zt_pool_em_df = ak.stock_zt_pool_em(date='20210525')
  File "/usr/local/lib/python3.9/site-packages/akshare/stock_feature/stock_ztb_em.py", line 50, in stock_zt_pool_em
    temp_df.columns = [
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 1 elements, new values have 17 elements

**Comment by albertandking** [comment]
> stock_zt_pool_em

接口正常，只能获取近期的数据

**Comment by hua060097** [comment]
> > stock_zt_pool_em
> 
> 接口正常，只能获取近期的数据

import akshare as ak

stock_zt_pool_em_df = ak.stock_zt_pool_em(date='20240325')
print(stock_zt_pool_em_df)
换了时间也报了一样的错

**Comment by hua060097** [comment]
@albertandking
