### ISSUE TITLE
 'stock_intraday_sina'接口不可用

### ISSUE THREAD

**Issue by Garenzhou** [akfamily/akshare#4961]
# 详细描述遇到的问题
（用的最新版本） 'stock_intraday_sina'接口不可用，实际api好像加了反爬逻辑，返回码是200，但是内容是空数组，同样参数有网页端https://vip.stock.finance.sina.com.cn/quotes_service/view/cn_bill.php?symbol=sz000001 发起的请求却表现正常

# 接口的名称和相应的调用代码
import akshare as ak
print(ak.stock_intraday_sina())

# 接口报错的截图或描述
Traceback (most recent call last):
  File "D:\PycharmProjects\learningvnpy\main.py", line 22, in <module>
    print(ak.stock_intraday_sina())
  File "C:\Users\Garen\.conda\envs\vnpy\lib\site-packages\akshare\stock\stock_intraday_sina.py", line 110, in stock_intraday_sina
    big_df.sort_values(by=["ticktime"], inplace=True, ignore_index=True)
  File "C:\Users\Garen\.conda\envs\vnpy\lib\site-packages\pandas\core\frame.py", line 7176, in sort_values
    k = self._get_label_or_level_values(by[0], axis=axis)
  File "C:\Users\Garen\.conda\envs\vnpy\lib\site-packages\pandas\core\generic.py", line 1910, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'ticktime'

# 期望获得的正确结果
作为唯一的历史tick（非单日）数据接口，还是希望能正常使用

**Comment by albertandking** [comment]
> stock_intraday_sina

接口测试正常
