### ISSUE TITLE
stock_share_change_cninfo接口异常

### ISSUE THREAD

**Issue by c07290** [akfamily/akshare#5078]
代码：
df = ak.stock_share_change_cninfo(symbol=’000001‘, start_date=‘19930101’, end_date=‘20240726’)

报错：
Traceback (most recent call last):
  File "D:\anaconda3\envs\python39\lib\site-packages\pandas\core\indexes\base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '公告日期'

**Comment by albertandking** [comment]
请按 issues 要求提交问题
