### ISSUE TITLE
AKShare 接口问题报告 | AKShare Interface Issue Report

### ISSUE THREAD

**Issue by YP-Ye** [akfamily/akshare#5331]
> 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容 |
> Welcome to join "Data Science in Practice" Knowledge
> Community for discussions on financial data and quantitative investment.
>
> 详细信息参考 | For detailed information, please visit:：https://akshare.akfamily.xyz/learn.html

## 前提 | Prerequisites

遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级 | Before reporting any issues, please upgrade
your AKShare to the **latest version** using the following command:：

```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8 | Python version requirement ≥ 3.8
```

## 如何提交问题 | How to Submit an Issue

提交问题的同时，请提交以下相关信息，以更精准的解决问题。| Please provide the following information when
submitting an issue for more accurate problem resolution.

**不符合提交规范的 issues 会被关闭！** | **Issues that don't follow these guidelines will be closed!**

**详细问题描述** | Detailed Problem Description

1. 请先详细阅读文档对应接口的使用方式 | Please read the documentation thoroughly for the
relevant interface：https://akshare.akfamily.xyz
2. 操作系统版本，目前只支持 64 位操作系统 | Operating system version (64-bit only supported)
win11 64位
3. Python 版本，目前只支持 3.8 以上的版本 | Python version (must be 3.8 or above)
3.11.5
4. AKShare 版本，请升级到最新版 | AKShare version (please upgrade to latest)
1.15.21
5. 接口的名称和相应的调用代码 | Interface name and corresponding code
```
import akshare as ak

crypto_hist_df = ak.crypto_hist(symbol="BTC", period="每日", start_date="20151020", end_date="20201023")
print(crypto_hist_df)
```
6. 接口报错的截图或描述 | Screenshot or description of the error
```
>>> import akshare as ak
C:\Anaconda3\Lib\site-packages\akshare\__init__.py:2947: UserWarning: 为了支持更多特性，请将 Pandas 升级到 2.2.0 及以上版本！
  warnings.warn(
>>>
>>> crypto_hist_df = ak.crypto_hist(symbol="BTC", period="每日", start_date="20151020", end_date="20201023")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\Lib\site-packages\akshare\crypto\crypto_hist_investing.py", line 177, in crypto_hist
    temp_df = pd.read_html(r.text)[0]
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\pandas\io\html.py", line 1205, in read_html
    return _parse(
           ^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\pandas\io\html.py", line 1006, in _parse
    raise retained
  File "C:\Anaconda3\Lib\site-packages\pandas\io\html.py", line 986, in _parse
    tables = p.parse_tables()
             ^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\pandas\io\html.py", line 262, in parse_tables
    tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\pandas\io\html.py", line 618, in _parse_tables
    raise ValueError("No tables found")
ValueError: No tables found
```
7. 期望获得的正确结果 | Expected correct results
正常获得加密货币日线数据

**Comment by YP-Ye** [comment]
看到接口不支持了。
