### ISSUE TITLE
AKShare 接口问题报告 | 调用上海证券交易所-股票数据总貌接口报错

### ISSUE THREAD

**Issue by chenminghua8** [akfamily/akshare#5434]
## 前提 | Prerequisites
使用版本为：1.15.47。

**详细问题描述** | Detailed Problem Description
执行与报错如下：
>>> stock_sse_summary_df = ak.stock_sse_summary()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/apple/.local/lib/python3.10/site-packages/akshare/stock/stock_summary.py", line 203, in stock_sse_summary
    data_json = r.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by albertandking** [comment]
> stock_sse_summary

请按 issues 模板提交问题
