### ISSUE TITLE
AKShare 接口问题报告 | 调用深圳证券交易所-市场总貌-证券类别统计接口报错

### ISSUE THREAD

**Issue by chenminghua8** [akfamily/akshare#5435]
使用版本为：1.15.47。

详细问题描述
执行与报错如下：
>>> stock_szse_summary_df = ak.stock_szse_summary(date="20241216")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/apple/.local/lib/python3.10/site-packages/akshare/stock/stock_summary.py", line 39, in stock_szse_summary
    temp_df = pd.read_excel(BytesIO(r.content), engine="openpyxl")
  File "/home/apple/.local/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 495, in read_excel
    io = ExcelFile(
  File "/home/apple/.local/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1567, in __init__
    self._reader = self._engines[engine](
  File "/home/apple/.local/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py", line 553, in __init__
    super().__init__(
  File "/home/apple/.local/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 573, in __init__
    self.book = self.load_workbook(self.handles.handle, engine_kwargs)
  File "/home/apple/.local/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py", line 572, in load_workbook
    return load_workbook(
  File "/home/apple/.local/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 346, in load_workbook
    reader = ExcelReader(filename, read_only, keep_vba,
  File "/home/apple/.local/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 123, in __init__
    self.archive = _validate_archive(fn)
  File "/home/apple/.local/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 95, in _validate_archive
    archive = ZipFile(filename, 'r')
  File "/usr/lib/python3.10/zipfile.py", line 1272, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.10/zipfile.py", line 1339, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by albertandking** [comment]
> 使用版本为：1.15.47。
> 
> 详细问题描述 执行与报错如下：
> 
> > > > stock_szse_summary_df = ak.stock_szse_summary(date="20241216")
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/home/apple/.local/lib/python3.10/site-packages/akshare/stock/stock_summary.py", line 39, in stock_szse_summary
> > > > temp_df = pd.read_excel(BytesIO(r.content), engine="openpyxl")
> > > > File "/home/apple/.local/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 495, in read_excel
> > > > io = ExcelFile(
> > > > File "/home/apple/.local/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1567, in **init**
> > > > self._reader = self._engines[engine](
> > > > File "/home/apple/.local/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py", line 553, in **init**
> > > > super().**init**(
> > > > File "/home/apple/.local/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 573, in **init**
> > > > self.book = self.load_workbook(self.handles.handle, engine_kwargs)
> > > > File "/home/apple/.local/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py", line 572, in load_workbook
> > > > return load_workbook(
> > > > File "/home/apple/.local/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 346, in load_workbook
> > > > reader = ExcelReader(filename, read_only, keep_vba,
> > > > File "/home/apple/.local/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 123, in **init**
> > > > self.archive = _validate_archive(fn)
> > > > File "/home/apple/.local/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 95, in _validate_archive
> > > > archive = ZipFile(filename, 'r')
> > > > File "/usr/lib/python3.10/zipfile.py", line 1272, in **init**
> > > > self._RealGetContents()
> > > > File "/usr/lib/python3.10/zipfile.py", line 1339, in _RealGetContents
> > > > raise BadZipFile("File is not a zip file")
> > > > zipfile.BadZipFile: File is not a zip file

请按 issues 模板提交问题
